### ISSUE TITLE
Add support for setting the namespaces for V4M logging and monitoring components

### ISSUE THREAD

**Issue by dwstern** [sassoftware/viya4-deployment#108]
https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#monitoring-and-logging lists variables we can set in e.g. $HOME/project/deploy/${NS}/${NS}-viyavars.yaml, to customize the cluster-logging,cluster-monitoring and viya-monitoring components of SAS Viya Monitoring for Kubernetes. For example, we can use this file to set the Kibana and Grafana passwords (V4M_KIBANA_PASSWORD and V4M_GRAFANA_PASSWORD respectively), among many other thngs.

Please would you add a way to set the LOG_NS (logging namespace) and MON_NS (monitoring namespace) in this vars file too? These namespace names should not be hard-coded to 'logging' and 'monitoring' respectively; you can change them if you deploy SAS Viya Monitoring for Kubernetes the manual way.

**Comment by thpang** [comment]
Fixed here #143

**Comment by dwstern** [comment]
Fantastic news - thank you @thpang!
