### ISSUE TITLE
Error while Ansible usage

### ISSUE THREAD

**Issue by YuryShkoda** [sassoftware/viya4-deployment#116]
Script:
```
ansible-playbook \
  -e BASE_DIR=$HOME/viya4-deployment \
  -e CONFIG=$HOME/viya4-deployment/ansible-vars.yaml \
  -e TFSTATE=$HOME/viya4-deployment/terraform.tfstate \
  -e JUMP_SVR_PRIVATE_KEY=$HOME/viya4-deployment/keys/id_rsa \
  playbook.yaml --tags "baseline,viya,cluster-logging,cluster-monitoring,viya-monitoring,install"
```
Error:
```TASK [baseline : Include nfs-subdir-external-provisioner] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'community.kubernetes.helm'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/home/aliust/projects/viya4-deployment/roles/baseline/tasks/nfs-subdir-external-provisioner.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Remove deprecated nfs-client-provisioner\n  ^ here\n"}

 

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=23   changed=3    unreachable=0    failed=1    skipped=12   rescued=0    ignored=0 
```

**Comment by NormJohnIV** [comment]
Did you install the needed dependencies? https://github.com/sassoftware/viya4-deployment/blob/main/docs/user/AnsibleUsage.md#initialize-ansible

**Comment by YuryShkoda** [comment]
Thank you, @NormJohnIV !
Your suggestion helped.

**Comment by venu-ibex-9** [comment]
How I need create this terraform.tfstate file, from where can i get

**Comment by venu-ibex-9** [comment]
Hi @YuryShkoda , I am getting this below error, can you help me please

TASK [common : Parse tfstate] **************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'tfstate'. Error was a <class 'ansible.errors.AnsibleFileNotFound'>, original message: Could not find or access '/Users/venugopal/sas-viya/viya4-iac-aws/viya4-deployment/terraform.tfstate' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by enderm** [comment]
you want to point use the tfstate file from your luster creation (if using one of the viya4-iac-* projects to create your k8s cluster)

**Comment by venu-ibex-9** [comment]
thanks for the info, that was mention in the document it will be very useful for beginners

**Comment by enderm** [comment]
It's right there on main readme:
https://github.com/sassoftware/viya4-deployment#terraform-state-file

**Comment by venu-ibex-9** [comment]
got it  thanks
