### ISSUE TITLE
kubernetes via pip---will this version work?

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-deployment#119]
Installing collected packages: kubernetes
Successfully installed kubernetes-17.17.0
root@henmo:~/project/viya4-deployment

I am trying to deploy viya4.

**Comment by thpang** [comment]
If you start [here](https://go.documentation.sas.com/doc/en/sasadmincdc/v_016/itopssr/n1ika6zxghgsoqn1mq4bck9dx695.htm#p064jn2z8uhlp5n1xtln8i0uh74f) with the Viya 4 docs you can see that at a minimum you'll need kubernetes 1.18 to start. The version you're trying to use is not supported.

**Comment by henmo09** [comment]
ok i ma installing kubernets 19
