### ISSUE TITLE
Variables information

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-deployment#123]
I have deployed kubernetes using IAC in Azure, now I want to deploy Viya sas using ansible. One of the required variables is

V4_CFG_ORDER_NUMBER | SAS order number | string |   | true |   | viya
Where do i get this SAS order NUmber???
this is what i downloaded from SAS
root@henmo:~/software# ls -l
total 872
drwxr-xr-x 3 root root   4096 Jul 21 22:05 Viya4_2020.1.5
-rwx------ 1 root root 887458 Jul 21 21:57 Viya4_2020.1.5.zip
root@henmo:~/software# cd Viya4_2020.1.5/
root@henmo:~/software/Viya4_2020.1.5# ls -l
total 1208
-rw-r--r-- 1 root root 811795 May 14 12:37 SASViyaV4_9CJ2PL_1_stable_2020.1.5_20210514.1620994953000_deploymentAssets_2021-05-14T163626.tgz
-rw-r--r-- 1 root root  34953 May 14 12:38 SASViyaV4_9CJ2PL_1_stable_2020.1.5_license_2021-05-14T163319.jwt
-rw-r--r-- 1 root root   4210 May 14 12:38 SASViyaV4_9CJ2PL_certs.zip
-rw-r--r-- 1 root root 371817 May 14 12:57 viya4-9cj2pl-toc.html

**Comment by thpang** [comment]
It appears you already have your order number: 9CJ2PL

**Comment by henmo09** [comment]
ok thanks

**Comment by venu-ibex-9** [comment]
hi @henmo09 , from where you got SAS order number, can you please help me.
