### ISSUE TITLE
Deploy Pre-reqs in AKS with NFS storage' Fails - Looking for Openshift?

### ISSUE THREAD

**Issue by milohiggo** [sassoftware/viya4-deployment#124]
Hi Team, I am trying to deploy the Pre-reqs in AKS with NFS storage,  using the docker container, but it continually fails (without creating anything) with the following error:

###################################################################################################################################

TASK [baseline : Remove deprecated efs-provisioner namespace] ***********************************************************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'openshift'

fatal: [localhost]: FAILED! => {"changed": false, "error": "No module named 'openshift'", "msg": "Failed to import the required Python library (openshift) on bf8e4dded2cf's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP **************************************************************************************************************************

localhost                  : ok=22   changed=2    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0

Tuesday 27 July 2021  07:36:35 +0000 (0:00:00.783)       0:00:06.391 **********

===============================================================================

baseline : Remove deprecated nfs-client-provisioner -------------------------------------------------------------------------- 1.43s

baseline : Remove deprecated efs-provisioner --------------------------------------------------------------------------------- 1.30s

baseline : Remove deprecated efs-provisioner namespace ----------------------------------------------------------------------- 0.78s

Gathering Facts -------------------------------------------------------------------------------------------------------------- 0.77s

common : tfstate - export kubeconfig ----------------------------------------------------------------------------------------- 0.58s

global tmp dir --------------------------------------------------------------------------------------------------------------- 0.28s

baseline role ---------------------------------------------------------------------------------------------------------------- 0.07s

baseline : Include nfs-subdir-external-provisioner --------------------------------------------------------------------------- 0.06s

common role ------------------------------------------------------------------------------------------------------------------ 0.05s

common : Add nat ip to LOADBALANCER_SOURCE_RANGES ---------------------------------------------------------------------------- 0.05s

common : tfstate - cluster name ---------------------------------------------------------------------------------------------- 0.04s

common : tfstate - nfs path -------------------------------------------------------------------------------------------------- 0.04s

common : tfstate - provider -------------------------------------------------------------------------------------------------- 0.04s

common : Parse tfstate ------------------------------------------------------------------------------------------------------- 0.04s

common : tfstate - cluster node pool mode ------------------------------------------------------------------------------------ 0.04s

common : tfstate - jump server ----------------------------------------------------------------------------------------------- 0.04s

common : tfstate - jump user ------------------------------------------------------------------------------------------------- 0.04s

common : tfstate - jump rwx filestore path ----------------------------------------------------------------------------------- 0.04s

common : tfstate - kubeconfig var -------------------------------------------------------------------------------------------- 0.04s

common : tfstate - cluster autoscaler location ------------------------------------------------------------------------------- 0.04s

################################################################################################################################

I don't know why it looking for Openshift when this cluster is in AKS. 

I rechecked the ansible-vars.yaml file - it has PROVIDER:  azure   -- see below

[sas@master-node viya4-deployment]$ head ansible-vars.yaml

## Cluster

PROVIDER: azure

CLUSTER_NAME: ssaghi-aks

NAMESPACE: viya4nfs

I have also tried running it with ansible, but alas - the same error.

Any light on the above would be appreciated

**Comment by thpang** [comment]
Did you try running the `baseline,install` again? It seem it could not pull the required needed `openshift` item.

**Comment by milohiggo** [comment]
Why is it trying to pull the Openshift item, when I'm trying to deploy on AKS? But, yes I tried many times - no joy, same error.

**Comment by thpang** [comment]
How are you running the code with Ansible or Docker? If Ansible what version of Python is on your machine?

**Comment by milohiggo** [comment]
I have tried both the ansible and the docker approach - both yield the same result as above i.e. it keeps looking for the openshift item.

**Comment by thpang** [comment]
Have you tried to download the needed item by hand outside the script to see if the machine has access to the internet for that item? Or is something else keeping that library from loading? I am asking as I did a deployment when you opened this issue and have found no problems deploying in AWS/Azure/GCP

**Comment by milohiggo** [comment]
One thing I did do was remove the current image and re-pull the docker image from as specified in the PSGEL298 course and it ran fine - i.e. I re-ran the same docker script to create the Pre-Reqs and it ran fine. One thing, I haven't tried is removing the existing docker image and rebuilding it again. Will try this out and report back.

**Comment by milohiggo** [comment]
Hi - I re-pulled the image and re-ran - all seems fine. Not sure what happened on the previous pull, but it's all working fine now, as such, please mark this issue as resolved. - Thanks
