### ISSUE TITLE
all pods crashing after successfull deployment

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-deployment#128]
lookin at oone of the pods, kubectl logs does not show anything but describe shows.
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  16m                 default-scheduler  Successfully assigned viya4-frg-v1/sas-logon-app-764795d975-ps8pb to aks-stateless-38049675-vmss000000
  Normal   Pulled     16m (x3 over 16m)   kubelet            Container image "cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-certframe:3.7.2-20201208.1607438373197" already present on machine
  Normal   Started    16m (x3 over 16m)   kubelet            Started container sas-certframe
  Normal   Created    13m (x4 over 16m)   kubelet            Created container sas-certframe
  Warning  BackOff    62s (x56 over 16m)  kubelet            Back-off restarting failed container
root@henmo:~/project/viya4-deployment# kubectl describe pod sas-logon-app-764795d975-ps8pb -n viya4-frg-v1

**Comment by henmo09** [comment]
any  help here please

**Comment by henmo09** [comment]
more info
viya4-deployment# kubectl get pods -A |grep logon
viya4-frg-v1    sas-logon-app-764795d975-ps8pb                                  0/1     Init:CrashLoopBackOff   10         27m
root@henmo:~/project/viya4-deployment# kubectl exec   sas-logon-app-764795d975-ps8pb -n viya4-frg-v1 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "sas-logon-app" out of: sas-logon-app, sas-certframe (init)
error: unable to upgrade connection: container not found ("sas-logon-app")

**Comment by thpang** [comment]
You're not providing any information here. If you're having issues with SAS Viya running in the cluster you'll need to find out if the images are being pulled, which they appear to be from the info you shared. You'll need to identify what in the cluster is not working for SAS Viya and interrogate those pods. If you have not read the docs, here is the [SAS Viya 4 documentation](https://go.documentation.sas.com/doc/en/sasadmincdc/v_016/sasadminwlcm/home.htm) link. Not much more to help with here, you've not provided much information.

**Comment by henmo09** [comment]
IAC using terraform was deployed successfully.

Command:
root@henmo:~/project/viya4-deployment# ansible-playbook   -e BASE_DIR=$HOME/project/viya4-deployment   -e CONFIG=$HOME/project/viya4-deployment/ansible-vars.yaml   -e TFSTATE=$HOME/project/viya4-iac-azure/terraform.tfstate   -e JUMP_SVR_PRIVATE_KEY=$HOME/.ssh/id_rsa   playbooks/playbook.yaml --tags "baseline,viya,install


VIya sas ansible deployment was working successfully, although it was successfull, i recorded the output, this is the only error found:
alhost] => {"changed": true, "cmd": ["kubectl", "--kubeconfig", "/tmp/ansible.8tr74yoz/.kube", "apply", "-n", "viya4-frg-v1", "--selector=sas.com/admin=namespace", "-f", "/root/project/viya4-deployment/kubeviya-aks/viya4-frg-v1/site.yaml", "--prune"], "delta": "0:00:14.458619", "end": "2021-08-14 18:19:36.852782", "failed_when_result": false, "msg": "non-zero return code", "rc": 1, "start": "2021-08-14 18:19:22.394163", "stderr": "Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress\nWarning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress\nError from server (Invalid): error when creating \"/root/project/viya4-deployment/kubeviya-aks/viya4-frg-v1/site.yaml\": Ingress.extensions \"sas-event-stream-processing-metering-app\" is invalid: [spec.rules[0].host: Invalid value: \"viya4_frg.ingress.com\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: \"viya4_frg.ingress.com\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]\nError

Logs and describe does not show enough information at all other than the one I provided. I have not checked every single one. As you mentioned I checkec cache and logon pods, nothing informational in the logs that lead to the issue.

**Comment by henmo09** [comment]
OK that was fixed, no errors on the output for ansible deployment.
Pods still not running but i have  a different error.
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  8m19s                  default-scheduler  Successfully assigned viya4-frg-v1/sas-logon-app-5649dc7f64-9krww to aks-stateless-38049675-vmss000000
  Normal   Pulled     8m14s                  kubelet            Container image "cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-certframe:3.7.2-20201208.1607438373197" already present on machine
  Normal   Created    8m9s                   kubelet            Created container sas-certframe
  Normal   Started    8m8s                   kubelet            Started container sas-certframe
  Warning  Failed     5m46s                  kubelet            Failed to pull image "cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-logon-app:2.39.9-20201002.1601645502383": rpc error: code = FailedPrecondition desc = failed to pull and unpack image "cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-logon-app:2.39.9-20201002.1601645502383": failed commit on ref "layer-sha256:e1f6b366065c7812f6046058705acac95885ec6f616e384cf86700469b34b680": "layer-sha256:e1f6b366065c7812f6046058705acac95885ec6f616e384cf86700469b34b680" failed size validation: 341 != 342: failed precondition

**Comment by thpang** [comment]
That's an issue with the container registry and not the tooling. You'll have to reach out to folks there. Could also be related to your order if it has had content updates. Againk, not much to go on.

**Comment by enderm** [comment]
are there any updates on this issue? @henmo09 if this can be closed, please let us know. Also, if it has been solved, please do share the steps that led to a solution.

**Comment by thpang** [comment]
No response from @henmo09 closing.
