### ISSUE TITLE
 ssh: connect to host issue

### ISSUE THREAD

**Issue by venu-ibex-9** [sassoftware/viya4-deployment#140]
I am getting this below issue , do i need to open port 22 manually on that server?

Failed to connect to the host via ssh: ssh: connect to host 50.16.214.175 port
22: Operation timed out

TASK [jump-server : jump-server - lookup groups] *******************************
fatal: [localhost -> 50.16.214.175]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}

PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=3    unreachable=0    failed=1    skipped=31   rescued=0    ignored=0

**Comment by enderm** [comment]
you didn't provide enough information here. Please share at least the contents of your ansible vars settings, and information about how you created the k8s environment.

You are asking whether you need to open port 22 manually on "that server", which, I assume means the jump VM. 
I agree that a closed network port is a likely  cause here. You are free to open that port manually (or programmatically) and see if that helps. 

There are also ways to set up the viya4-iac-* and viya4-deployment parameters so that you do not need to do that extra step.

Some points to check:

If you used one of the viya4-iac-* projects to create your k8s cluster, double-check that you set the correct CIDR range) for client access (https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/CONFIG-VARS.md#admin-access). You can verify that by trying to log  into your jump host by using ssh from the same client where your are running your ansible playbook.

Once the ssh login works, make sure that you specified the correct ssh key for your ansible play. It should be same one you specified as "ssh_public_key" when you created your cluster (https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/CONFIG-VARS.md#required-variables), and also the one you used when trying to login to your jump VM via ssh (the JUMP_SVR_PRIVATE_KEY setting: https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#jump-server)

**Comment by venu-ibex-9** [comment]
Hi @enderm , i provisioned the k8s via viya4-iav and i am folllowing viya4-deployment guide. please see my variable file here

## Cluster
NAMESPACE: ibexlabs

## MISC
DEPLOY: true # Set to false to stop at generating the manifest
LOADBALANCER_SOURCE_RANGES: []


## Storage 
V4_CFG_MANAGE_STORAGE: true

## SAS API Access
V4_CFG_SAS_API_KEY: 'xxxxxxxxxxx'
V4_CFG_SAS_API_SECRET: 'xxxxxxxxx'
V4_CFG_ORDER_NUMBER:  <order_number>

## CR Access
V4_CFG_CR_USER: <container_registry_user>
V4_CFG_CR_PASSWORD: <container_registry_password>

## Ingress
V4_CFG_INGRESS_TYPE: ingress
V4_CFG_INGRESS_FQDN: <desired_fqdn>
V4_CFG_TLS_MODE: "full-stack" # [full-stack|front-door|disabled]

## Postgres


## LDAP
V4_CFG_EMBEDDED_LDAP_ENABLE: true

## Consul UI
V4_CFG_CONSUL_ENABLE_LOADBALANCER: true

## SAS/CONNECT
V4_CFG_CONNECT_ENABLE_LOADBALANCER: true

## Monitoring and Logging
## uncomment and update the below values when deploying the viya4-monitoring-kubernetes stack
#V4M_BASE_DOMAIN: <base_domain>

**Comment by enderm** [comment]
There you are: you set
LOADBALANCER_SOURCE_RANGES: []

That means to you will not be able to access anything in your cluster deployment - neither the JUMP vm nor the cluster api endpoint.
Please review this section (or the equivalent section for your iac cloud project, if you are not using azure): viya4-iac-azure/CONFIG-VARS.md at main * sassoftware/viya4-iac-azure (github.com)<https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/CONFIG-VARS.md#admin-access>

Also check the comments for the *_cidrs variable in any of the examples tfvars files (e.g. viya4-iac-azure/sample-input.tfvars at main * sassoftware/viya4-iac-azure (github.com)<https://github.com/sassoftware/viya4-iac-azure/blob/main/examples/sample-input.tfvars>

**Comment by venu-ibex-9** [comment]
I added my NAT ip there, but i am getting this belwo error

TASK [jump-server : jump-server - add host] ************************************
changed: [localhost]
Friday 03 September 2021  13:03:18 +0000 (0:00:00.132)       0:00:09.609 ****** 
[WARNING]: Unhandled error in Python interpreter discovery for host localhost:
Failed to connect to the host via ssh: Warning: Permanently added
'50.16.214.175' (ECDSA) to the list of known hosts.  jumpuser@50.16.214.175:
Permission denied (publickey).

TASK [jump-server : jump-server - lookup groups] *******************************
fatal: [localhost -> 50.16.214.175]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"50.16.214.175\". Make sure this host can be reached over ssh: Warning: Permanently added '50.16.214.175' (ECDSA) to the list of known hosts.\r\njumpuser@50.16.214.175: Permission denied (publickey).\r\n", "unreachable": true}

**Comment by enderm** [comment]
I am repeating the verification steps I posted earlier. 

Verify that by trying to log into your jump host by using ssh from the same client where your are running your ansible playbook.

Once the ssh login works, make sure that you specified the correct ssh key for your ansible play. It should be same one you specified as "ssh_public_key" when you created your cluster (https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/CONFIG-VARS.md#required-variables), and also the one you used when trying to login to your jump VM via ssh (the JUMP_SVR_PRIVATE_KEY setting: https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#jump-server)

**Comment by venu-ibex-9** [comment]
Hi thanks for the update,  i tried to connect my jumpbox vm from my local machine but I am getting permission denied issue,can you help me how can i fix this issue, i changed the permission of file and tried but no luck. please help me on this.
FYR:-


ssh jumpuser@54.209.82.131
The authenticity of host '54.209.82.131 (54.209.82.131)' can't be established.
ECDSA key fingerprint is SHA256:k4ezIzL/8roO3VglLNIyyn3JC1urSuKYvxnHoUHkoNs.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '54.209.82.131' (ECDSA) to the list of known hosts.
Enter passphrase for key '/Users/venugopal/.ssh/id_rsa': 
jumpuser@54.209.82.131: Permission denied (publickey).

**Comment by enderm** [comment]
that shows us that you have physical access to your VM

Now the question is whether the ssh key matches the one you used when creating the cluster. Please check that.

**Comment by venu-ibex-9** [comment]
Thanks @enderm , thst issue got resolved. i got order number not founfd issue. wher i get this order number?

FYR:-
atal: [localhost]: FAILED! => {"changed": true, "cmd": ["/tmp/ansible.ddxw9z6l/viya4-orders-cli", "license", "--file-path", "/data/sas-test-eks/ibexlabs/site-config", "--file-name", "license", "u003e", "lts", "2020.1"], "delta": "0:00:00.497688", "end": "2021-09-04 12:08:05.579712", "msg": "non-zero return code", "rc": 1, "start": "2021-09-04 12:08:05.082024", "stderr": "2021/09/04 12:08:05 INFO: no config file found\n2021/09/04 12:08:05 ERROR: asset request failed: {\"version\":2,\"httpStatusCode\":404,\"message\":\"Not Found\",\"errors\":[{\"message\":\"Order U003E not found\"}]}", "stderr_lines": ["2021/09/04 12:08:05 INFO: no config file found", "2021/09/04 12:08:05 ERROR: asset request failed: {\"version\":2,\"httpStatusCode\":404,\"message\":\"Not Found\",\"errors\":[{\"message\":\"Order U003E not found\"}]}"], "stdout": "", "stdout_lines": []}

**Comment by venu-ibex-9** [comment]
This issue was also resolved,I deployed successfully without failures. How I can verify the SAS deployment, is there any document on this @enderm

**Comment by enderm** [comment]
Verify Deployment: https://go.documentation.sas.com/doc/en/sasadmincdc/v_017/calvalid/titlepage.htm
The SAS Documentation is always a good place to look a first stop to find answers.

Please share how you resolved the issue. It will help others who run into similar issues understand what can go wrong and how to solve it.
