### ISSUE TITLE
Postgres Ansible task fails when no value is provided

### ISSUE THREAD

**Issue by GonzaloUlla** [sassoftware/viya4-deployment#147]
## Summary

Per [CONFIG-VARS.md#postgres](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#postgres), `default` and `default.internal` keys are always required.

To minize configuration effort, I recommend adding default values for those keys.

### Current behavior

When `default.internal` key is not set, [Postgres Ansible task](https://github.com/sassoftware/viya4-deployment/blob/main/roles/vdm/tasks/postgres/postgres.yaml) fails with error: 

```log
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'internal'` 
```

### Expected behavior

[Postgres Ansible task](https://github.com/sassoftware/viya4-deployment/blob/main/roles/vdm/tasks/postgres/postgres.yaml) runs successfully using a default value for `default.internal` key.

**Comment by thpang** [comment]
Given the default does not know if it's internal vs external. The current empty value in the iac sample file will stay empty. The end user will have to read the docs and be aware of how their database is being configured. There error you are seeing is correct. It's telling you to fill in the value.
