### ISSUE TITLE
'PROVIDER' is undefined

### ISSUE THREAD

**Issue by SASDAVIRO** [sassoftware/viya4-deployment#151]
we are deploying SAS Viya 4, and running the asnible with baseline, we have this error:
TASK [baseline : Include cluster-autoscaler] ******************************************************************************************************************
task path: /Users/hector.pineda/adl_github/viya/luis_21/devops-anly-viya-aws/environments/dev/templates/viya/viya4-deployment-villas/roles/baseline/tasks/main.yaml:38
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'PROVIDER == \"aws\"' failed. The error was: error while evaluating conditional (PROVIDER == \"aws\"): 'PROVIDER' is undefined\n\nThe error appears to be in '/Users/hector.pineda/adl_github/viya/luis_21/devops-anly-viya-aws/environments/dev/templates/viya/viya4-deployment-villas/roles/baseline/tasks/main.yaml': line 38, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Include cluster-autoscaler\n  ^ here\n"
}

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0  

--

**Comment by thpang** [comment]
So guessing from the last comment you made it past your issue. Closing this one out.
