### ISSUE TITLE
V4_CFG_INGRESS_FQDN setup

### ISSUE THREAD

**Issue by Pav-Bahia** [sassoftware/viya4-deployment#154]
i assume the load balancer or Firewall or whatever is chosen for V4_CFG_INGRESS_FQDN
needs to be added to IAC  azure project as i do not see it in Variable.tf for azure.
i can see the config for egress load balancer, 
also does this have to be a load balancer.

**Comment by thpang** [comment]
When you run `baseline,install` that will install your `ingress-nginx`. If you need to handle your own ingress you'll need to remove that namespace and all elements around `ingress-nginx` from your deployment. Then in the cluster you'll have to setup by hand whatever you're looking to do.
