### ISSUE TITLE
Manage storageclass

### ISSUE THREAD

**Issue by Pav-Bahia** [sassoftware/viya4-deployment#155]
Could you please confirm as part of the prep for k8s
Manage storageclass
is this to chnage the default storage class.

Thx in advance.

**Comment by thpang** [comment]
No. Once you have run the `baseline,install` step to baseline the cluster a `sas` storage class is created. Development teams are encouraged to use this; however, if they don't they are open to changes in whatever Storage Class is setup as the default for a given provider.

**Comment by Pav-Bahia** [comment]
so i am correct in saying once i run

ansible-playbook \
  -e CONFIG=$HOME/ansible-vars-iac.yaml \
  -e TFSTATE=$HOME/viya4-iac-aws/terraform.tfstate \
  viya4-deployment --tags "baseline,viya,cluster-logging,cluster-monitoring,viya-monitoring,install"

and then check storage with the below command i will also see sas as listed storage in addition to below 

kubectl get storageclass

AME                PROVISIONER                                     RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile           kubernetes.io/azure-file                        Delete          Immediate              true                   23d
azurefile-premium   kubernetes.io/azure-file                        Delete          Immediate              true                   23d
default (default)   kubernetes.io/azure-disk                        Delete          WaitForFirstConsumer   true                   23d
managed-premium     kubernetes.io/azure-disk                        Delete          WaitForFirstConsumer   true                   23d
nfs-client          cluster.local/nfs-subdir-external-provisioner   Delete          Immediate              true                   3h7m

**Comment by thpang** [comment]
Yes, but what I can see here is your have `nfs-client` as one of your storage class types and not `sas` It seems you're using a very old version of the `viya4-deployment` code base. You should upgrade.

**Comment by Pav-Bahia** [comment]
Ok will do..
last question, is the baseline and deploy a 2 step procedure of can it all be done one go 
i assume the tag in 
viya4-deployment --tags  
determines what is done ie baseline etc etc.
