### ISSUE TITLE
sasboot or viya_admin for sitedefault file 

### ISSUE THREAD

**Issue by pbahia** [sassoftware/viya4-deployment#165]
Please could you confirm if 
the site default file creates admin as viya_admin as unable to logon with sasboot and the defined password in the vdm/file/sitedefault.yaml 

pasword has not been updated in the file 

stable
2021.1.6

Thx

**Comment by thpang** [comment]
Yes by default if you use the OpenLDAP included, it sets up viya_admin and it's password. This user has admin rights. If you're not able to login you need to check your system something else is a miss. I'd check your pods and ensure they are running correctly especially the sas-logon pod.

**Comment by pbahia** [comment]
i am able to logon with viya_admin..
So if im reading this correctly sasboot is not setup when using the sitedefault.yaml file instead its setup as viya_admin with OpenLDAP.
is this only with 2021.1.6, as i only changed the cadence in the main.yaml file from 2021.1.5 to 2021.1.6..
in the previous version  2021.1.5 sasboot was setup and i was able to logon with the password in the file sitedefault.yaml 

Just need some clarification on deployments and sasboot using the deployment files.
currently only viya_admin works not sasboot

Thx

**Comment by thpang** [comment]
If you're using the IAC/Deployment repos this has been in place since day one. If you're looking for answers on sasboot this is not the place.

**Comment by pbahia** [comment]
Ok.. Not sure how sasboot started working then in 2021.1.5.. if it was meant to be viya_admin that only worked using IAC files
