### ISSUE TITLE
Azure StorageClass and deployment wizard 

### ISSUE THREAD

**Issue by DaveFos** [sassoftware/viya4-deployment#175]
I am using the ansible based deployment for 2021.1.6.  The directions require creating an entry in the kustimization.yaml file for patches. 
How do I get kuerneties and sas to notice this change.  if I rerun the install it erases the patches section.

**Comment by thpang** [comment]
Hi @DaveFos 

If you look here in the [README.md](https://github.com/sassoftware/viya4-deployment#customize-deployment-overlays) file you see how to use your kustomization patches. 

Hope this helps.

Thomas

**Comment by thpang** [comment]
Closing this one no response. Thanks.
