### ISSUE TITLE
need to delete sas-pyconfig job to avoid errors during "manifest - deploy"

### ISSUE THREAD

**Issue by gwsas** [sassoftware/viya4-deployment#177]
To avoid this error

TASK [vdm : manifest - deploy] *************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "--kubeconfig", "/example/kubeconfig.conf", "apply", "-n", "example-ns", "--selector=sas.com/admin=namespace", "-f", "/example/site.yaml", "--prune"], "delta": "0:00:09.260891", "end": "2022-01-11 21:50:41.959327", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2022-01-11 21:50:32.698436", "stderr": "The Job \"sas-pyconfig\" is invalid: spec.template: Invalid value: 

The playbook will need to delete the sas-pyconfig job before this (and handle an error if the job doesn't exist yet) as instructed in the doc

[SAS Help Center: Update to a New Version Manually](https://go.documentation.sas.com/doc/en/sasadmincdc/v_022/k8sag/p0cc5i51v7t370n1q6a1n8n4bcsy.htm)

If you are updating to 2021.1.4, skip this step.
The sas-pyconfig job was introduced in version 2021.1.5. If there is a sas-pyconfig job, delete it:
kubectl -n name-of-namespace delete job sas-pyconfig

and here

[SAS Help Center: Apply a Patch Update Manually](https://go.documentation.sas.com/doc/en/sasadmincdc/v_022/k8sag/p1exl6m22st6min1i3yxex279mxa.htm)

For versions 2021.1.5 and later, delete the sas-pyconfig job with the following command:
kubectl -n name-of-namespace delete job sas-pyconfig

**Comment by thpang** [comment]
Unless sas-pyconfig has a manifest that is applied into the cluster this is outside of the scope here. If there is a need to have the manifest modified for this product in the kustomization.yaml then we can work on making changes based on cadence. @gwsas can you provide that information. If this is strictly a manual adjustment this will have to be taken care of before the update is applied to the cluster.

**Comment by gwsas** [comment]
In that case, I would recommend a note in the Readme (and/or the ansible/docker usage mds) to inform people to perform all the pertinent manual steps/deployment notes on their own before using viya4-deployment to update their Viya 4 version.
This came from a support ticket to SAS tech support, so apparently it wasn't clear to the customer they would need to handle these things manually.

**Comment by thpang** [comment]
Hi @gwsas , the information you said was not in the README is actually [here](https://github.com/sassoftware/viya4-deployment#customize-deployment-overlays). The flow of the doc does steer the user in the right direction with the flow. We're reviewing now to see if we can surface this to make it more apparent.

**Comment by gwsas** [comment]
Currently, I don't really see anything there that would lead me to the [Deployment Notes](https://go.documentation.sas.com/doc/en/sasadmincdc/v_025/dplynotes/titlepage.htm) or [Manual Update](https://go.documentation.sas.com/doc/en/sasadmincdc/v_025/k8sag/p0cc5i51v7t370n1q6a1n8n4bcsy.htm) sections of the official doc to look for all the manual things I need to do before running viya4-deployment to go from, say, 2021.2.4 to 2021.2.5.
In other words, for this scenario, what would lead me from the viya4-deployment README to [Required Updates by Component](https://go.documentation.sas.com/doc/en/sasadmincdc/v_025/k8sag/p0cc5i51v7t370n1q6a1n8n4bcsy.htm#n0atm18myjkk07n1lu3zljq7ow4s) where it tells me to delete the sas-pyconfig job?  If I'm the rare admin that reads and understands everything, there's a slight chance I might get there from here.

Anyway, sounds good if there will be some note/alert/clarification added in the future that steers admins to review the manual steps in the doc.

**Comment by sayeun** [comment]
We added a section for manual update a while back.  You can see it in the README [Updating SAS Viya Manually](https://github.com/sassoftware/viya4-deployment/blob/main/README.md#updating-sas-viya-manually) 
Closing this as complete.
