### ISSUE TITLE
Cookie file /rabbitmq/data/.erlang.cookie must be accessible by owner only

### ISSUE THREAD

**Issue by bullcity42** [sassoftware/viya4-deployment#182]
The viya4-deployment project creates site-config/vdm/transformers/sas-storageclass.yaml from a template. That yaml modifies all statefulsets to use whatever the user set for V4_CFG_STORAGECLASS which, in some cases, is sas-azurefile if customer follows the doc. RabbitMQ is controlled by a statefulset, so as a result, Rabbit is using their sas-azurefile storage (which supports RWX with permissions 777). Rabbit only needs RWO. We think the easiest way to resolve this is for the viya4-deployment project to modify the last line of roles/vdm/templates/transformers/sas-storageclass.yaml to exclude Rabbit. ie:

       annotationSelector: sas.com/component-name notin (sas-risk-cirrus-search,sas-workload-orchestrator,sas-rabbitmq-server)

Note: Internal reference number is 7613487275

**Comment by thpang** [comment]
We don't officially support AzureFile.

The 2 currently supported items are NFS - for the standard storage and an enterprise storage - for HA storage. Both are setup to use the 'sas' storage class.

If a user/customer has modified the `V4_CFG_STORAGECLASS` to use another storage class, that's on them.

The selector can be altered in the running cluster as well by the cluster to adjust the above recommendation.

**Comment by thpang** [comment]
@bullcity42 can you provide more information here? Looking to see what storage class the `sas-rabbitmq-server` typically use. Do you use the default storage class, create your own for use, these are the questions we need answered. You can't base your coding on a specific providers component as you've stated above `Aurefile` as this is not supported in all providers. When we have an answer we'll revisit. If needed reach-out internally and we can chat.

**Comment by sayeun** [comment]
We still don't officially support AzureFile. 
Due to inactive in this ticket, marking as stale. If there are further questions/concerns please response back or open a new GitHub issue.
