### ISSUE TITLE
(IAC-320) Support for path based routing on Logging and Monitoring

### ISSUE THREAD

**Issue by mikegigawatt** [sassoftware/viya4-deployment#193]
When manually deploying the Logging and Monitoring applications, there is an option to deploy the logging and monitoring end points as path based routing instead of host based routing.  This removes the requirement of the wildcard SAN entry on the TLS certificate and the wildcard update to DNS.  For deployments in Azure in particular, this is the a recommended approach in the configuration files.  it moves the access end point for kibana from:
https://kibana.myingress.mydomain.com
to
https://myingress.mydomain.com/kibana
Is it possible to incorporate this modification into the existing framework? I have been running the script to generate the base deployment for logging and monitoring, adding the configuration to do path based routing, and then manually deploying the logging and monitoring environments post change.

**Comment by sayeun** [comment]
This was fixed by #386
