### ISSUE TITLE
Tool wants to install openshift 0.12.0 while deploying to AWS EKS

### ISSUE THREAD

**Issue by milohiggo** [sassoftware/viya4-deployment#203]
Why is the tool trying to install the Python Openshift client - see 

viya4-deployment/docs/user/Dependencies.md:pip3 | openshift | 0.12.0
viya4-deployment/docs/user/Dependencies.md:pip_openshift_version | the version of openshift to install from pip
viya4-deployment/docs/user/Dependencies.md:     --build-arg pip_openshift_version=0.12.0 \

The tool is then trying to perform a network route map for Openshift - see
viya4-deployment/roles/vdm/vars/main.yaml:  route: "route.openshift.io"

I am trying to configure this for AWS EKS - how do I avoid all these Openshift requirements?

**Comment by thpang** [comment]
The tooling in this repo does not focus on a specific cloud provider. The tooling here is generic and is used to create a suitable environment for the SAS Viya software in a given kubernetes cluster. If you're looking to configure an AWS EKS cluster your best bet is to look [here](https://github.com/sassoftware/viya4-iac-aws).

**Comment by thpang** [comment]
Talked with @milohiggo and need to re-open this one. He's providing more information from the ansible output.

**Comment by thpang** [comment]
Working with @milohiggo to determine what is happening in his env to cause this issue. it is not wide spread and seems to be a configuration in his env that might be causing the problem.
