### ISSUE TITLE
Kustomize - Generate deployment manifest fails - when deploying to AWS EKS (missing Namespace)

### ISSUE THREAD

**Issue by milohiggo** [sassoftware/viya4-deployment#207]
When attempting to use the DaC tool (version 4.9.0) to deploy Viya onto an AWS EKS cluster, the tool fails on the TASK [vdm : kustomize - Generate deployment manifest] with the error:

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kustomize", "build", "/data/ssaghi-sas-non-production-dev-cluster/dev-viya-ns", "--load_restrictor=none", "-o", "/data/ssaghi-sas-non-production-dev-cluster/dev-viya-ns/site.yaml"], "delta": "0:00:13.066208", "end": "2022-04-07 07:34:20.102503", "msg": "non-zero return code", "rc": 1, "start": "2022-04-07 07:34:07.036295", "stderr": "Error: merging from generator &{0xc000f8fe00 {ingress-input } {{ ingress-input merge {[INGRESS_HOST=ssaghi] [] []} <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:\"\", Version:\"v1\", Kind:\"ConfigMap\"}, Name:\"ingress-input\", Namespace:\"\"} does not exist; cannot merge or replace", "stderr_lines": ["Error: merging from generator &{0xc000f8fe00 {ingress-input } {{ ingress-input merge {[INGRESS_HOST=ssaghi] [] []} <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:\"\", Version:\"v1\", Kind:\"ConfigMap\"}, Name:\"ingress-input\", Namespace:\"\"} does not exist; cannot merge or replace"], "stdout": "", "stdout_lines": []}
```

It looks like the namespace variable is empty. The tool completes successfully if only the  --tags "baseline,install" are used. Attached is the full log, which also include the kustomize file from the project.
[220407-DaC-run.zip](https://github.com/sassoftware/viya4-deployment/files/8448832/220407-DaC-run.zip)

I used the IAC tool to create the EKS cluster and then used the following to execute the tool using the Docker image, created from this project:
docker run --rm \
  --group-add root \
  --user $(id -u):$(id -g) \
  --volume $BASEDIR:/data \
  --volume $DEPLOYDIR/mb-ansible-vars.yaml:/config/config \
  --volume $TFSTATE/terraform.tfstate:/config/tfstate \
  --volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key \
  viya4-deployment --tags "baseline,viya,install"

Expected results: The Viya software will be deployed into the EKS cluster

**Comment by dhoucgitter** [comment]
Hi @milohiggo, could you share the content of your mb-ansible-vars.yaml file, I didn't see it in the zip you attached.

**Comment by milohiggo** [comment]
See attached.
[mb-ansible-vars.zip](https://github.com/sassoftware/viya4-deployment/files/8460136/mb-ansible-vars.zip)

**Comment by milohiggo** [comment]
Solved- it appears the .kube/config file also needs to be included as a volume mount eg:
docker run --rm \
  --group-add root \
  --user $(id -u):$(id -g) \
  --volume $BASEDIR:/data \
  --volume $HOME/.kube/config:/.kube/kubeconfig \
  --volume $DEPLOYDIR/mb-ansible-vars.yaml:/config/config \
  --volume $TFSTATE/terraform.tfstate:/config/tfstate \
  --volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key \
  viya4-deployment --tags "baseline,viya,install"

This issue can now be closed

**Comment by thpang** [comment]
The kube config file should not need to be included if its in your tfstate file. You might want to investigate and run the command using the `-it --entrypoint` option in order to view inside the container and see how the mounts and tfstate file information is being passed in.
