### ISSUE TITLE
(IAC-560) how to add users to the embedded OpenLDAP

### ISSUE THREAD

**Issue by wweghe** [sassoftware/viya4-deployment#219]
Hi,
In the section of the Readme.md on the OpenLDAP Customizations, it is stated : 
"Subsequently, you can either delete and redeploy the OpenLDAP server with a new configuration, or add users using ldapadd."

I tried the latter (using ldapadd) and indeed users are created to the OpenLDAP, and can be used in Viya 4. 
However, upon a restart of the OpenLDAP pod, the newly added users are no longer there, only the original users (user1, user2 and viya_admin).
So it would seem the OpenLDAP pods do not have persistent storage attached, and only the users available in this file "site-config/vdm/generators/openldap-bootstrap-config.yaml" are available after a restart of the OpenLDAP pod.

Is my understanding correct, or am I missing something ?

**Comment by thpang** [comment]
That is correct. OpenLDAP does not persist and gets created and destroyed within the SAS Viya name space it is created.

This ldap server is setup as temporary stop-gap for folks who have not gotten that far in their enterprise integration with the Viya 4 deployment.If you need something that persists you'll need to install an ldap server outside of the Viya 4 namespace. 

[Here](https://go.documentation.sas.com/doc/en/sasadmincdc/v_026/calids/n1aw4xnkvwcddnn1mv8lxr2e4tu7.htm) is the SAS documentation on how to integrate LDAP with the SAS Viya 4 software.

**Comment by thpang** [comment]
Yeah we could clear that up a bit.
