### ISSUE TITLE
Download Deployment Assets before executing the DAC

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#220]
As I understand when running the viya4-deployment DAC scripts to install Viya 4, the tool will download the deployment assets
Is there an option if I have already downloaded the deployment assets beforehand and allow the DAC script to utilize this instead of downloading a new one?

**Comment by lorenzk1213** [comment]
Goal here is to download deployment assets, perform some customizations on the assets e.g. manifest file and then once complete run the tool to install.

**Comment by thpang** [comment]
Closing this one.
