### ISSUE TITLE
Use Deployment Operator For Administering the Viya 4 environment after installation using viya 4 deployment DAC

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#221]
Would like to check if it is possible to use Deployment Operator For Administering the Viya 4 environment after installation using the viya4-deployment DAC. Anything required to keep in mind?

Thanks

**Comment by thpang** [comment]
Have reached out to the Deployment Operator team for a response. Waiting to see what they have to say.

**Comment by nbattala** [comment]
@thpang Any updates on this please?

**Comment by dhoucgitter** [comment]
@lorenzk1213, viya4-deployment introduced support for installing Viya using the Deployment operator in release [6.0.0 - December 19, 2022](https://github.com/sassoftware/viya4-deployment/releases/tag/6.0.0).  See the [Deployment Operator Notes](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#base) for information on using the Deployment Operator with DAC including use of the `V4_DEPLOYMENT_OPERATOR_ENABLED` configuration variable in the viya4-deployment project.
Using DAC Release 6.0.0 or later that is configured to deploy Viya using the Deployment Operator will allow you to continue using the the Deployment Operator for Administering Viya 4 after your installation. Refer to this [SAS documentation](https://documentation.sas.com/?cdcId=itopscdc&cdcVersion=default&docsetId=itopscon&docsetTarget=p0839p972nrx25n1dq264egtgrcq.htm) for instructions on using the deployment operator.
