### ISSUE TITLE
Customization for relocating SASWORK is not treated properly

### ISSUE THREAD

**Issue by sasbxs** [sassoftware/viya4-deployment#223]
This is further documented in tech support track: https://sirius.na.sas.com/Sirius/GSTS/ShowTrack.aspx?trknum=7613571759

I am trying to ensure that SASWORK is pointing to a hostPath rather than the emptyDir that it points to by default.  The approach to this is supposed to be modification of the change-viya-volume-storage-class.yaml file located at: sas-bases/examples/sas-programming-environment/storage.  FYI, I'm working from the documentation here: https://go.documentation.sas.com/doc/en/sasadmincdc/v_024/calsrvpgm/n0k315nlna2awln119phkhua1na2.htm on a 2021.2.4 deployment.

When I copy that file into  a directory under site-config and modify it for my hostPath, site.yaml will not build.  It appears that the VIya 4 Deployment project picks up the customization, but doesn't represent it properly in kustomization.yaml (it's treating a patch as a resource according to tech support).

What appears in kustomization.yaml is:

resources:
...
  - site-config/sas-programming-environment/change-viya-volume-storage-class.yaml

But what it *should* be putting in kustomization.yaml (again, according to tech support) is:

patches:
  - path: site-config/change-viya-volume-storage-class.yaml
    target:
      kind: PodTemplate
      labelSelector: "sas.com/template-intent=sas-launcher"

I have been able to work around this (I think), as I have gotten site.yaml to build but I can't attempt applying it until tonight when my environment's users are finished for the day.  I'm working around by doing the following:

1. I moved the change-viya-volume-storage-class.yaml file out of the site-config directory so that it does not get picked up by the ansible job.
2. I've changed my ansible-vars file so that deploy is set to false.
3. I've created a bash script that run the ansible playbook, then appends the "patches" block from above to the end of the kustomization.yaml file that ansible has created, and finally rebuilds site.yaml based on this modified kustomization.yaml file.

While I'm optimistic that this approach will work, every customer deployment should be leveraging this patch as the emptyDir default can cause all sorts of problems and it seems like there should be an easier way.   Relocating SASWORK should not require re-engineering of the whole deployment process.  Is there a different approach I should be taking entirely?

**Comment by thpang** [comment]
Can you provide errors that are output from that keep the site.yaml from building. Thanks.

**Comment by sasbxs** [comment]
Thomas,

There is more information on this situation here that includes tech support's analysis of the problem:
7613571759 - Challenges relocating SASWORK on Viya 2021.2.4<https://sirius.na.sas.com/Sirius/GSTS/ShowTrack.aspx?trknum=7613571759>

The ansible log is available here: file://l10g725/Users/sasbxs/Downloads/Tech_Support_05MAY2022 (these are the same files that correspond to the tech support track)
Thank link also contains the kustomization.yaml file that ansible produces as well as a tarball of the deployment directory.  I've also just dropped into that location a copy of my current kustomization.yaml file - which builds correctly (manually), and is the product of my inserting the proper patch information *after* running the ansible playbook.

Please reach out if you have further questions.

Cheers,
Brian

**Comment by thpang** [comment]
Closing this one as well. Items was addressed in the support ticket and we'll be revisiting the storage classes for products in a future release of the DAC tooling.
