### ISSUE TITLE
msg": "Failure when executing Helm command. Exited 1.\nstdout: Release "ingress-nginx" does not exist. Installing it now.

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#225]
When deploying he baseline Viya4 components, ingress-nginx,, nfs, cert-manager using the below command:

```bash
docker run --rm \
  --group-add root \
  --user $(id -u):$(id -g) \
  --volume $BASEDIR:/data \
  --volume $HOME/.kube/config:/.kube/kubeconfig \
  --volume $DEPLOYDIR/dev-ans-vars.v1.0.1.yaml:/config/config \
  --volume $TFSTATE/terraform.tfstate:/config/tfstate \
  --volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key \
  viya4-deployment --tags "baseline,install" -vvv
```

Its failing on the ingress-nginx portion with below error message
 
"msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"ingress-nginx\" does not exist. Installing it now.\n\nstderr: Error: timed out waiting for the condition\n",
    "stderr": "Error: timed out waiting for the condition\n",
    "stderr_lines": [
        "Error: timed out waiting for the condition"
    ],
    "stdout": "Release \"ingress-nginx\" does not exist. Installing it now.\n",
    "stdout_lines": [
        "Release \"ingress-nginx\" does not exist. Installing it now."
    ]

Can anyone help on this issue pls?

![error](https://user-images.githubusercontent.com/104424321/168002103-8326a843-c1ee-4fd8-a62b-5d9d6427304e.JPG)
![Load balancer empty](https://user-images.githubusercontent.com/104424321/168002115-c371f35b-2b76-43c5-bb3c-37b95148fa21.JPG)
[Log.txt](https://github.com/sassoftware/viya4-deployment/files/8675342/Log.txt)

Also if I understand correctly, once this gets completed successfully, I would be able to see a Load balancer entry in AWS?

Thanks in advance,

**Comment by thpang** [comment]
Did you setup your default cidr ranges correctly this looks like a security/firewall issue keeping traffic from flowing.

**Comment by lorenzk1213** [comment]
Hi thpang,

On the tfvars file of the iac we have set the following
default_public_access_cidrs = []

(Last time when we set a value we hit an error like The following CIDRs are not allowed in publicAccessCidrs: [10.239.0.0/16, 10.162.0.0/16])

while on the ansible vars yaml file for the viya4-deployment we have set
LOADBALANCER_SOURCE_RANGES: []

Could this be the reason of the issue?
Thanks

**Comment by thpang** [comment]
Yup that locks the cluster down. No allowed traffic. That would be why you're seeing the timeout issue. I'd look [here](https://github.com/sassoftware/viya4-iac-azure/blob/a5b9638ce18a84ce929892474f341321ce8a498b/docs/CONFIG-VARS.md#admin-access) in the docs to setup your infra correctly. Right now nothing can access your cluster. I would try using the kube config file and just running `kubectl cluster-info` to see if communication is working. Guessing it will not.

**Comment by lorenzk1213** [comment]
Hi thpang,

Below are the outputs of the commands seems connection is ok.:
kuebctl get nodes
kubectl cluster-info

![image](https://user-images.githubusercontent.com/104424321/169217003-57423fca-cdd9-403d-96cd-82a13f10caa8.png)

But still same issue is there. anything i can check further for this?

**Comment by thpang** [comment]
is this a public/private setup? Also if you can run the command with the -vvvv option to capture a bit more.

**Comment by AWSmith0216** [comment]
Have you tried looking at the resources (pods, services) in the ingress-nginx namespace, since that's what failed? Perhaps the controller pod isn't running, or the service hasn't been allocated an external IP.

**Comment by lorenzk1213** [comment]
Hi Adam,

The pods inside ingress-nginx namespace seems to be running.

***@***.***


Though I notice that EXTERNAL-IP is currently in pending state.

***@***.***

Anything can be checked further?

Thanks
Regards,
Lorenz

**Comment by AWSmith0216** [comment]
If you do a describe on the service with the pending external IP, what reason is given for the pending state?

**Comment by lorenzk1213** [comment]
@AWSmith0216 
This is the describe output. 
Seems no definitive reason for the pending state. though there is a message of "Ensuring load balancer" under Message column in Event Section.  

![image](https://user-images.githubusercontent.com/104424321/169722318-c0f8e3ef-6f20-4c41-b8ad-c655167e2561.png)

**Comment by lorenzk1213** [comment]
Found this in stackoverflow
https://stackoverflow.com/questions/70621367/external-ip-remains-pending-on-controller-service-after-installation-of-nginx-in

Tried the steps by running the deploy.yaml

After running I now have an External IP and A record in AWS.

Any changes required on the viya4-deployment scripts?

![image](https://user-images.githubusercontent.com/104424321/169732873-8df38655-bea7-4986-9538-bada637dc0b3.png)


![image](https://user-images.githubusercontent.com/104424321/169732907-0b0719ae-7267-47b9-9751-d65d6fec6b34.png)

**Comment by lorenzk1213** [comment]
Hi,

Please advise as well if the workaround found in https://stackoverflow.com/questions/70621367/external-ip-remains-pending-on-controller-service-after-installation-of-nginx-in is ok to be applied and will not break anything.

Thanks

**Comment by dhoucgitter** [comment]
Hi @lorenzk1213, I expect that you may have resolved this already, however, as you have noted that this is a private setup, setting the DAC configuration variable `V4_CFG_INGRESS_MODE=private` should handle setting the same `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` annotation on the ingress-nginx controller that you referenced in the stackoverflow workaround. As such, if you applied that manually you should be getting the "aws-load-balancer-internal" annotation that you need for your private configuration.

**Comment by dhoucgitter** [comment]
The original issue was resolved and the previous comment provides instructions to have DAC annotate the ingress-nginx controller as needed for a private IP configuration. Closing as resolved.
