### ISSUE TITLE
Ingress for Viya 4 in AWS

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#226]
After running the baseline components to install the prereqs for Viya 4 using the below command:

docker run --rm \
--group-add root \
--user $(id -u):$(id -g) \
--volume $BASEDIR:/data \
--volume $HOME/.kube/config:/.kube/kubeconfig \
--volume $DEPLOYDIR/dev-ans-vars.v1.0.1.yaml:/config/config \
--volume $TFSTATE/terraform.tfstate:/config/tfstate \
--volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key \
viya4-deployment --tags "baseline,install" -vvv

The execution completed successfully, however seems A record / load balancer still does not exist in AWS I assume it should now be existing after successful execution of the baseline components? Please let me know if my understanding is correct as well. If yes, may I know what could be the possible issue?

Below is the screenshot of the LB

![image](https://user-images.githubusercontent.com/104424321/168767742-58a5b32a-59e2-4256-935b-bea6d0c74623.png)

attaching the log as well.
[Uploading baseline_prereqs_install.log…]()

As noticed as well, seems External IP is in pending state
![image](https://user-images.githubusercontent.com/104424321/168768825-04b06549-33ad-4e3e-9ac5-5472e2529402.png)

Could this be the reason?

**Comment by thpang** [comment]
Not knowing how you setup your infrastructure, it looks like your load balancer is is off. Can you check in the AWS portal and trouble shoot from that side?

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are additional questions, please open a new [Github issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).

**Comment by dhoucgitter** [comment]
Closed #226 as completed.
