### ISSUE TITLE
Unable to deploy with docker usage

### ISSUE THREAD

**Issue by ceciivanov** [sassoftware/viya4-deployment#227]
I'm getting the below error when i'm trying to deploy with docker run, 
 {"msg": "The task includes an option with an undefined variable. The error was: 'CLUSTER_NAME' is undefined\n\nThe error appears to be in '/viya4-deployment/roles/common/tasks/main.yaml': line 202, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set DEPLOY_DIR\n  ^ here\n"}
 
 Maybe is something with the directories and paths ?, but i did everything as it said in the docker usage.md 
 any help?

**Comment by thpang** [comment]
If you can pass along the docker command you're using. Something is not defined as it states. Thanks.

**Comment by ashagraw91** [comment]
Thanks @dhoucgitter  for the reply, actually I used that initially and i was getting this error:

fatal: [localhost]: FAILED! => changed=false 
  ansible_facts: {}
  ansible_included_var_files: []
  message: 'an error occurred while trying to read the file ''/config/config'': [Errno 21] Is a directory: b''/config/config'''

This was my script
`sudo docker run --rm --group-add root --user $(id -u):$(id -g) --volume $HOME/deployment-yaml/deployments:/data --volume $HOME/deploy-viya/xyz-xyz-simulator/viya4-deployment/ansible-vars.yaml:/config/config --volume $HOME/statefile/viya.tfstate:/config/tfstate --volume $HOME/deploy-viya/xyz-xyz-simulator/viya4-iac-azure/.ssh/id_rsa:/config/jump_svr_private_key/id_rsa lll.azurecr.io/viya4-deployment:latest --tags "baseline,viya,install" -vvv`

**Comment by dhoucgitter** [comment]
Hi @ceciivanov, were you able to resolve your issue? If not, could you post the docker command that you are using.

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are additional questions, please open a new [Github issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).

**Comment by dhoucgitter** [comment]
Closed #227 as completed.
