### ISSUE TITLE
Issue in installing metric-server

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#230]
Hi, When installing the baseline components prereqs, the execution stopped with the following error:

  "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"metrics-server\" does not exist. Installing it now.\n\nstderr: Error: timed out waiting for the condition\n",
    "stderr": "Error: timed out waiting for the condition\n",
    "stderr_lines": [
        "Error: timed out waiting for the condition"
    ],
    "stdout": "Release \"metrics-server\" does not exist. Installing it now.\n",
    "stdout_lines": [
        "Release \"metrics-server\" does not exist. Installing it now."
    ]
}

Any ideas?

Command used:

docker run --rm --group-add root --user $(id -u):$(id -g) --volume $BASEDIR:/data --volume $HOME/.kube/config:/.kube/kubeconfig --volume $DEPLOYDIR/dev-ans-vars.v1.0.1.yaml:/config/config --volume $TFSTATE/terraform.tfstate:/config/tfstate --volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key viya4-deployment --tags "baseline,install" -vvv

Attaching full log.
[baseline.log](https://github.com/sassoftware/viya4-deployment/files/8804127/baseline.log)

Please advise,
Thanks

**Comment by thpang** [comment]
Looks like a network issues. The log seems to indicate you can talk with your cluster. Did you try again?

**Comment by lorenzk1213** [comment]
@thpang,

Have perform deletion prior to rerunning the install by running following commands:
kubectl delete deploy metrics-server -n kube-system
kubectl delete svc metrics-server -n kube-system

Have tried to rerun, after execution, it was observed that fail=0 but seems it did not install the metrics-server.

![image](https://user-images.githubusercontent.com/104424321/171375685-10ed6629-bf04-4b31-8a00-e05930fb7e97.png)

Below is the log.

[baseline_prereq_install_after_delete_metrics-server.txt](https://github.com/sassoftware/viya4-deployment/files/8812952/baseline_prereq_install_after_delete_metrics-server.txt)

Anything we have missed to delete or something?

Thank you.

**Comment by thpang** [comment]
It did not reinstall as it found evidence of the metrics server. It is showing that the metrics-server's service is still there. So yes it will simply skip the install metrics-server step and not re-install. You'll need to either clean up ALL of the metrics-server items by hand or run the `baseline,uninstall` command to clean up the baseline and then run `baseline,install` to re-install it cleanly.

**Comment by lorenzk1213** [comment]
@thpang. 

Seems this is ok now. Thanks..
metrics-server pod is now running.
