### ISSUE TITLE
Pods not Running after deployment

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#231]
Hi,

Deployed Viya 4 using the github scripts. Execution seems completed with failed=o.
However seems SAS pods are not in Running State. Suggestions on where to check?

[deploy viya4.log](https://github.com/sassoftware/viya4-deployment/files/8822983/deploy.viya4.log)

[sas-consul-server-0_describe.log](https://github.com/sassoftware/viya4-deployment/files/8822988/sas-consul-server-0_describe.log)
[pods_output.txt](https://github.com/sassoftware/viya4-deployment/files/8822991/pods_output.txt)

**Comment by dhoucgitter** [comment]
@lorenzk1213, were you able to resolve your issue?

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
