### ISSUE TITLE
Configure nginx ingress controller to support internal virtual private IP

### ISSUE THREAD

**Issue by ceciivanov** [sassoftware/viya4-deployment#234]
How can i change the approach of how nginx ingress controller is exposing the services to the outside world (with public IP). I'm thinking of something like VPN in azure and to set all of the networking of the cluster services only inside this virtual network so it can be private and accessible only to users inside the VPN. any ideas? thank you!

**Comment by ajeffowens** [comment]
Set the V4_CFG_INGRESS_MODE variable to "private" .. this should add the required annotation to the nginx controller service that forces Azure to create an internal LB.  

Your cluster identity will have to have appropriate permissions on the vnet.  (I typically just assign Contributor to the vnet's resource group)

**Comment by dhoucgitter** [comment]
@ceciivanov, are you still having the issue or were you able to resolve it?

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
