### ISSUE TITLE
sas-cas-server in Init Status after Install

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#235]
After running the deployment to install Viya 4,
All pods seems to be running fine

![image](https://user-images.githubusercontent.com/104424321/172584222-4fcd390b-dbc8-4bd9-8f6c-335873693db1.png)

except for sas-cas-server-default which is in Init Status
![image](https://user-images.githubusercontent.com/104424321/172584293-880579c0-e10b-4284-932c-cd8d28f823ac.png)

This is seen in the describe output

![image](https://user-images.githubusercontent.com/104424321/172584391-1ddcbb8c-886b-4e32-b712-be1d89b8ec51.png)

Appreciate any suggestions.

Thanks,

**Comment by lorenzk1213** [comment]
Hi @thpang 

We are using EFS in this environment and it was provisioned separately not using the IAC code. We map it by setting  V4_CFG_MANAGE_STORAGE: false in our ansible vars yaml file.

**Comment by lorenzk1213** [comment]
To add. one of the items we are wondering is where could this path be defined in the scripts:

our storage path is /viya-share/non-prod-dev-viya-ns however seems the deployment is reading it from //non-prod-non-prod-dev-viya-ns/viya-share/non-prod-dev-viya-ns

![image](https://user-images.githubusercontent.com/104424321/172810746-513dc931-8035-41c4-9253-1c9a21d8109f.png)

**Comment by thpang** [comment]
If you look in the `terraform output` you can you'll see these entries for your filestore:
`rwx_filestore_endpoint` and `rwx_filestore_path` these are the values that are used by the pods to mount into your storage.

**Comment by lorenzk1213** [comment]
@thpang 

This is the value from our terraform output for the 2 entries.

![image](https://user-images.githubusercontent.com/104424321/172984980-155f7ed0-d9d2-4b9e-b722-9db49e6512ad.png)

Seems rwx_filestore_path configured is "/" directory. But seems still different from the path the deployment reads which is //non-prod-non-prod-dev-viya-ns

Is it possible we have missed something?

Thanks,

**Comment by cceeci99** [comment]
Hello i have the same exact problem, but i haven't changed anything in terraform vars neither bring up custom nfs storage server
what could the error be ?

**Comment by lorenzk1213** [comment]
@cceeci99  May I see the output of the command:

kubectl get pods -n <namespace>
and
kubectl describe pod sas-cas-server-default-controller -n <namespace>

**Comment by cceeci99** [comment]
yeah i know with that command i got the exact same description, i think the problem is that the pods can't find the NFS storage to mount volumes

**Comment by thpang** [comment]
The // comes from the fact that a variable is not set which would include /viya-share so not quite sure what's a miss here. We never create paths with the // prefix.

**Comment by cceeci99** [comment]
I found the problem is that if you configure terraform to make its own network security group you must specify vm_public_access_cidrs so it can open an SSH port to the jumpuser, and when running the deployment with ansible, it will be able to connect to the jumpuser and make the directories that are needed. If it can't connect the ansible somehow manages to skip that error and doesn't create the directories but create all the deployments and that's why the sas-cas-controller could not mount the volumes

**Comment by thpang** [comment]
That is correct if there is no access to the vm's from ansible it will simply skip those steps without erroring. It's guessing you've handled those directories outside of the DAC code base. Did you set the default_public_access_cidr value or did you leave this empty?

**Comment by lorenzk1213** [comment]
@cceeci99  @thpang 

the default_public_access_cidr in our IAC .tfvars file is empty. Is it required for this to have a value?

![image](https://user-images.githubusercontent.com/104424321/173264120-e5ed7b39-52e5-441d-ba67-6df08b39c16d.png)

Also we did not configure the IAC to create a jumpbox as this was already provided by customer separately.

**Comment by cceeci99** [comment]
I have this as default meaning empty, because I do not want my resources to be accessed by any other IPs, as I have a VPN In my resource group and everything in the vnet will have access to them

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
