### ISSUE TITLE
Service unavailable 503

### ISSUE THREAD

**Issue by ceciivanov** [sassoftware/viya4-deployment#237]
After the deployment all workloads and pods are succeeded up and running except only one sas-connect-spawner which is in pending state. Also when i try to use the sas portal through the fqdn that i gave, it shows an error of 503 service unavailable, but i think that if i use the SASLogon/login path it takes me to the portal to login... any idea why is this happening? is the service available or not?

**Comment by thpang** [comment]
You'll need to check the state of the pods in your deployment. If sas-connect-spawner is in pending state you'd need to check the events on that pod as there won't be any logs. Need to see if the pod is being pulled or reason kubernetes is unhappy. Start there.

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are additional questions, please open a new [Github issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
