### ISSUE TITLE
Error when deploying 3rd Party tools in an private subnet on Azure

### ISSUE THREAD

**Issue by DoritozX** [sassoftware/viya4-deployment#241]
I would like to know if this script can be used to deploy Viya4 on an internal network. 
I tried to push the helm chart of third party tools such as nginx ingress or cert-manager to my own ACR and then specify INGRESS_NGINX_CHART_URL as the OCI URL of my ACR repository. 
But I got this error: "Error: looks like "oci://xxx.azurecr.io/helm/" is not a valid chart repository or cannot be reached: object required"
I want to know if this script support using OCI protocol, if not, is there any other way to deploy these third party components?
Thank you!

**Comment by ajeffowens** [comment]
Looks like there have been a number of issues with ACR as a helm OCI repository:  https://github.com/helm/helm/issues/8761 

Could be worth a shot to bump helm to latest and trying again.

If you are using the docker container, modify the Dockerfile of course... although the helm version in the Dockerfile currently is pretty recent and I wouldn't expect that to make a difference.

**Comment by thpang** [comment]
If you have not mirror the site exactly you can adjust [these variables](https://github.com/sassoftware/viya4-deployment/blob/main/roles/baseline/defaults/main.yml#L44-L46). This would allow you to use your own chart.

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are additional questions, please open a new [Github issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).

**Comment by dhoucgitter** [comment]
Closing #241 as completed.
