### ISSUE TITLE
Missing PVC Requirement for SAS® Risk Modeling

### ISSUE THREAD

**Issue by DidouJazz** [sassoftware/viya4-deployment#250]
Hi,
According to [Specify PersistentVolumeClaims to Use ReadWriteMany StorageClass](https://go.documentation.sas.com/doc/en/itopscdc/v_029/dplyml0phy0dkr/n08u2yg8tdkb4jn18u8zsi6yfv3d.htm#p0la9vh2963b2kn17f03ylvpiluu), there is a requirement for SAS® Risk Modeling to have one PVC called sas-risk-modeling-core.
I can see in the [sas-storageclass.yaml](https://github.com/sassoftware/viya4-deployment/blob/main/roles/vdm/templates/transformers/sas-storageclass.yaml) that sas-risk-cirrus-search seems always created but this is not true for sas-risk-modeling-core.
I'll temporarely add it to this yaml files but should we not add some logic to define if the product is in the order ?
Let me know your thoughts,
David

**Comment by DidouJazz** [comment]
Side-Note: I can "only" find the PVC definition called sas-risk-modeling-content-data : sas-bases/base/components/sas-risk-modeling-core/resources.yaml
Can this be a documentation issue, to define sas-risk-modeling-content-data and not  sas-risk-modeling-core ?

**Comment by dhoucgitter** [comment]
@DidouJazz, are you still having this issue?
