### ISSUE TITLE
update doc to include AWS specific environment variables to the AWS viya4-deployment docker container

### ISSUE THREAD

**Issue by markha73** [sassoftware/viya4-deployment#26]
-e AWS_ACCESS_KEY_ID=FOO -e AWS_SECRET_ACCESS_KEY=BAR -e AWS_DEFAULT_REGION=us-east-1

**Comment by thpang** [comment]
These items are not needed for the deployment code base. What is the reason you might need these. We're looking to close out some of these older issues. If you could provide an update.
