### ISSUE TITLE
Host based to Path based Ingress for Viya Monitoring and Logging

### ISSUE THREAD

**Issue by nachai9** [sassoftware/viya4-deployment#260]
Can some one pls add the functionality of converting the Host based Ingress to Path based Ingress for Logging and Monitoring, when we run the cluster-monitoring and cluster-logging using the ansible-playbook method with viya-deployment github code. This will be very helpful for Customers who will not need to make more DNS changes for Logging and Monitoring.

Example:
rules:
- host: dashboards.nachai2ns.stic.unx.sas.com
http:
paths:
- path: /

To
rules:
- host: nachai2ns.stic.unx.sas.com
http:
paths:
- path: /dashboards

**Comment by dhoucgitter** [comment]
Path-based routing for V4M was added under PR #386. The [`V4M_ROUTING`](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md?plain=1#L168) configuration variable was added in release [6.4.0 - March 30, 2023](https://github.com/sassoftware/viya4-deployment/releases/tag/6.4.0) to provide a choice of ingress options. Using that variable it is possible to select either `host-based`(the default) or `path-based` routing when using DAC to deploy Viya Monitoring and Logging.
