### ISSUE TITLE
ODBC and Other DB Configurations

### ISSUE THREAD

**Issue by azaadshatru** [sassoftware/viya4-deployment#269]
Can we add standard variables under viya-vars.yaml for automated deployment to apply the ODBC and Other standard DB configurations at the time of installation? Instead of manually changing the files and folders under site-config and applying updates.

**Comment by thpang** [comment]
You'll need to provide more information and examples

**Comment by dhoucgitter** [comment]
@azaadshatru, is this still an issue for you? 
If so, could you provide an example for how you manually change the files and folders under site-config and then apply updates. Are you trying to replace that process by using the viya-var.yaml file somehow? Also, could you post a link to SAS doc that refers to the viya-var.yaml that you reference?

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
