### ISSUE TITLE
Cadence name=lts / cadence version=2020.1 is not valid for order XXXXXX

### ISSUE THREAD

**Issue by simoncuceplexe** [sassoftware/viya4-deployment#273]
We part of the Get Licence step, we got  a fatal message

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/tmp/ansible.97_43q7x/viya4-orders-cli", "license", "--file-path", "/deployments/sas-viya-aks/default/site-config", "--file-name", "license", "9CQSQK", "lts", "2020.1"], "delta": "0:00:01.068394", "end": "2022-08-05 07:25:56.784645", "msg": "non-zero return code", "rc": 1, "start": "2022-08-05 07:25:55.716251", "stderr": "2022/08/05 07:25:55 INFO: no config file found\n2022/08/05 07:25:56 ERROR: asset request failed: {\"version\":2,\"httpStatusCode\":400,\"message\":\"Bad Request\",\"details\":[\"98531c7d-fc13-4586-aa41-77127648d2ec\"],\"errors\":[{\"message\":\"Cadence name=lts / cadence version=2020.1 is not valid for order ______\"}]}", "stderr_lines": ["2022/08/05 07:25:55 INFO: no config file found", "2022/08/05 07:25:56 ERROR: asset request failed: {\"version\":2,\"httpStatusCode\":400,\"message\":\"Bad Request\",\"details\":[\"98531c7d-fc13-4586-aa41-77127648d2ec\"],\"errors\":[{\"message\":\"Cadence name=lts / cadence version=2020.1 is not valid for order _________.\"}]}"], "stdout": "", "stdout_lines": []}

I have hidden the Order number

**Comment by terencet3** [comment]
You need to select the appropriate cadence version according to your software order as seen below:

![image](https://user-images.githubusercontent.com/110581531/183056793-10473088-bff0-459a-888e-a34a41d010c0.png)

You can specify this inside your **ansible-vars.yaml** file

Ex:
V4_CFG_ORDER_NUMBER:  'xxxxxxxx'  #SAS order number
V4_CFG_CADENCE_NAME: 'lts' # lts or stable
V4_CFG_CADENCE_VERSION: '2022.1' #cadence version

**Comment by thpang** [comment]
The cadence version in the log shows: cadence version=2020.1 which is not 2022.1 I believe you have a typo. Please verify

**Comment by simoncuceplexe** [comment]
That was the issue...thanks for the help
