### ISSUE TITLE
Issues while deploying baseline tools

### ISSUE THREAD

**Issue by azaadshatru** [sassoftware/viya4-deployment#295]
I am getting the following error while deploying baseline tools on ingress

TASK [baseline : Update INGRESS_NGINX_CONFIG] ****************************************************************************************************************************************************************
ok: [localhost]
Tuesday 13 September 2022  08:18:51 +0000 (0:00:00.031)       0:00:12.618 *****

TASK [baseline : Deploy ingress-nginx] ***********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  command: /usr/local/bin/helm --version=4.2.3 --repo=https://kubernetes.github.io/ingress-nginx upgrade -i --reset-values --wait --create-namespace -f=/tmp/tmp3o34uumq.yml ingress-nginx ingress-nginx
  msg: |-
    Failure when executing Helm command. Exited 1.
    stdout: Release "ingress-nginx" does not exist. Installing it now.

    stderr: Error: timed out waiting for the condition
  stderr: |-
    Error: timed out waiting for the condition
  stderr_lines: <omitted>
  stdout: |-
    Release "ingress-nginx" does not exist. Installing it now.
  stdout_lines: <omitted>

PLAY RECAP ***************************************************************************************************************************************************************************************************
localhost                  : ok=33   changed=4    unreachable=0    failed=1    skipped=32   rescued=0    ignored=0

urgent help is greatly appreciated

**Comment by azaadshatru** [comment]
though these items are getting created when the above errors occurs.
jumpuser@prd-sasviya4-jump-vm:~/project/deploy/prd-sasviya4-aks/sasviya4az$ kubectl get pods -n ingress-nginx
NAME                                        READY   STATUS    RESTARTS   AGE
ingress-nginx-controller-74446d9695-ftvc8   1/1     Running   0          16s
jumpuser@prd-sasviya4-jump-vm:~/project/deploy/prd-sasviya4-aks/sasviya4az$ kubectl get svc -n ingress-nginx
NAME                                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.0.139.205   <pending>     80:30418/TCP,443:30191/TCP   21s
ingress-nginx-controller-admission   ClusterIP      10.0.64.218    <none>        443/TCP                      21s
jumpuser@prd-sasviya4-jump-vm:~/project/deploy/prd-sasviya4-aks/sasviya4az$

**Comment by jawilk23** [comment]
Did you happen to find a resolution to this error? I am running into this exact issue.

**Comment by dhoucgitter** [comment]
@azaadshatru, what `V4_CFG_INGRESS_MODE` are you trying to configure. if it's `private`, see this [comment ](https://github.com/sassoftware/viya4-deployment/issues/234#issuecomment-1199261374)for a suggested setting and the annotation that it sets for you to create an internal LB.

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are additional questions, please open a new [Github issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
