### ISSUE TITLE
Viya monitoring is no longer operational when scaling down the nodes to stop the AWS EKS cluster

### ISSUE THREAD

**Issue by irchum** [sassoftware/viya4-deployment#296]
Hi Team,

I have opened this issue following an issue I raised with viya4-monitoring-kubernetes team.
https://github.com/sassoftware/viya4-monitoring-kubernetes/issues/397

Viya 4 has been deployed using viya4-deployment project on AWS. According to SAS PSD engineer, "we have to scale-down the nodes in the AWS EKS cluster to stop the cluster. After restarting the EKS cluster, we have encountered the following problem:
Viya Monitoring is no longer operational. We think that this is due to the corruption of the data store, as mentioned here ([#129](https://github.com/sassoftware/viya4-monitoring-kubernetes/issues/129))"

The potential solution, according to the above link, is to use a remove and redeploy process. They suggest using the scripts deploy_logging.sh and remove_logging.sh to perform these tasks (https://github.com/sassoftware/viya4-monitoring-kubernetes/tree/main/logging/bin)

With the Viya deployment project, the de-installation of cluster-logging and cluster-monitoring deletes everything including PV, PVCs and name spaces.

The engineer said, "these scripts are no longer available in the environment."

@gsmith-sas has provided the answer:
The Viya 4 Deployment project clones our project repo as part of the deployment process, runs the appropriate scripts and then cleans up after itself. This means the copy of our project repo is not available after deployment. It uses the same general process when removing things as well. Given this behavior, if you want to continue using Viya 4 Deployment, you would need to (re)clone our project repo after the initial deployment process to have access to our scripts (including the deploy_logging.sh and remove_logging.sh scripts).
https://github.com/sassoftware/viya4-monitoring-kubernetes/issues/397#issuecomment-1244559048

----
It looks that Viya Monitoring cannot be deployed with Viya deployment project as it removes Viya monitoring project repo after the deployment. The solution is to redeploy Viya Monitoring. 

Do you think a new feature that will be included in Viya deployment project in order to keep the Viya monitoring repo so that the appropriate scripts can be used rather than redeploying Viya Monitoring manually?

Thank you

Regards,
Ira

**Comment by dhoucgitter** [comment]
@irchum, please open a PM Request for this enhancement so that it can be considered, thanks.

**Comment by dhoucgitter** [comment]
After team discussion with PM we are closing this feature request that would preserve the Viya 4 monitoring repository content instead of removing it as is the current behavior. If you have a requirement to preserve the Viya 4 repo monitoring content in order to re-apply or otherwise re-run the same or other Viya 4 monitoring scripts at a later time, please download the Viya 4 monitoring project separately and follow that project's documentation and guidance for instructions.
