### ISSUE TITLE
Error when deploying already downloaded 'fast' cadence

### ISSUE THREAD

**Issue by nbattala** [sassoftware/viya4-deployment#326]
V4_CFG_CADENCE_NAME must be explicitly set to fast even though the deployment assets were manually downloaded and their path specified via V4_CFG_DEPLOYMENT_ASSETS and V4_CFG_LICENSE. Otherwise, this error is thrown:

V4_CFG_TLS_MODE is not ''disabled'', and your V4_CFG_CADENCE_VERSION is <= 2021.1, you must provide: V4_CFG_TLS_CERT, V4_CFG_TLS_KEY, V4_CFG_TLS_TRUSTED_CA_CERTS'

**Comment by riragh** [comment]
@nbattala, there have been updates to cert-manager and TLS cert variables along with other major changes. Also, `V4_CFG_CADENCE_VERSION is <= 2021.1` aren't supported. Please feel free to open new issue if this error persists new supported cadence versions.
