### ISSUE TITLE
Issue (Openstack cluster):  Release "ingress-nginx" does not exist. Installing it now.

### ISSUE THREAD

**Issue by sayalibhase** [sassoftware/viya4-deployment#330]
I am trying to use viya4 deployment DAC code on openstack cluster which is on-prem.
Using following command:
 docker run --rm   --group-add root   --user $(id -u):$(id -g)   --volume /openstack/deployments:/data   --volume /openstack/deployments/dev-cluster/.kube/config:/config/kubeconfig   --volume /root/openstack/deployments/dev-cluster/dev-namespace/ansible-vars.yaml:/config/config   --volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key   viya4-deployment --tags "baseline,viya,install"
 
 Error: 
![image](https://user-images.githubusercontent.com/115526036/199427011-c48c0c74-9d82-44b2-b19e-792da838f3de.png)

ingress controller is also running fine.
Please let me know what can be done next.

**Comment by thpang** [comment]
What provider did your create your IAC code base on for this one? AWS/Azure/GCP/OSS?

**Comment by riragh** [comment]
On-prem Openstack cluster setup works differently than the cloud provider. The steps documented in this project are recommended to be used in conjunction with SAS Viya4 IaC projects. Closing this issue, please feel free to reopen if more help is required.
