### ISSUE TITLE
failure in baseline install with tasks deleting or creating namespace (community.kubernetes.k8s plugin)

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-deployment#331]
While it was working well until recently, the playbook fails at baseline install see the error message below.

```sh
TASK [baseline : Remove deprecated efs-provisioner namespace] ***************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to get client due to openssl_md5() takes at most 1 argument (2 given)"}

PLAY RECAP ******************************************************************************************************************************localhost                  : ok=7    changed=0    unreachable=0    failed=1    skipped=52   rescued=0    ignored=0
```

in the log there is a second failure :

```sh
TASK [vdm : Create namespace] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to get client due to openssl_md5() takes at most 1 argument (2 given)"}
```
It looks like the namespace operations with community.kubernetes.k8s are not working anymore.
(tested with DAC 5.5.0 and 5.6.0 on a cluster created with viya4-iac-k8s).

Thanks

**Comment by thpang** [comment]
@raphaelpoumarede are you using the docker image or running ansible from the command line? Thx

**Comment by raphaelpoumarede** [comment]
Hi @thpang I'm using the ansible command line.

**Comment by thpang** [comment]
Those commands are running on `localhost` might be `helm` trying to run an old or outdated openssl command. You'd need to verify.

**Comment by raphaelpoumarede** [comment]
After talking with @thpang the problem was fixed by using the "kubernetes.os" plugin instead of the "community.kubernetes" plugin.
I made the changes globally in my local copy of the playbook with the following commands :

```sh
cd ~/viya4-deployment/roles
find . -type f -name "*.yaml" -exec sed -i 's/community.kubernetes./kubernetes.core./g' {} +
```

**Comment by mikegigawatt** [comment]
I hit a similar issue with the namespace flag not being recognized, and the fix that Raphael posted above worked for me as well.  +1.

**Comment by riragh** [comment]
Based on last comment, User managed to resolve the issue. Closing now.
