### ISSUE TITLE
TLS certs used in deployment aren't showing on webapp.

### ISSUE THREAD

**Issue by tclehman** [sassoftware/viya4-deployment#337]
I am trying to redeploy Viya with TLS certs I've generated in Azure Key vault. I generated a .pem key and pulled the .key from this to create the below documented files that are listed in the ansible-vars.yaml file. 

Ansible-vars.yaml screenshot of TLS configuration:
![image](https://user-images.githubusercontent.com/49881073/202009850-f725f3f6-6843-48e0-91cf-41566e338838.png)

After running the below deployment script, the deployment succeeds with no errors, however the webapp URL still shows that the site is "unsafe" and when I look at the certificate file in the browser, it shows the "Kubernetes Ingress Controller Fake Certificate" still.

Script used to deploy:

` 
sudo docker run --rm \
--group-add root \
--user $(id -u):$(id -g) \
--volume /deployments:/data \
--volume /home/azureuser/viya4-deployment/ansible-vars.yaml:/config/config \
--volume /home/azureuser/viya4-iac-azure/terraform.tfstate:/config/tfstate \
--volume /home/azureuser/viya4-deployment/pem:/pem \
--volume $HOME/.ssh/id_rsa:/config/jump_svr_private_key \
viya4-deployment --tags "baseline,viya,install"
`

Screenshot showing the install is still using the default certs:
![image](https://user-images.githubusercontent.com/49881073/202010231-b5d52647-eb27-4a70-be77-e82823e4f063.png)

Is there additional steps needed to deploy TLS certs to a Viya deployment? 

SAS Track: 7613686188

**Comment by tclehman** [comment]
I have figured out the problem. The cert file contained the private key, and the .key file was in an encoded format. The cert file needs to contain ONLY the cert, and the key file needs to contain the unencoded private key. 

Otherwise, the deployment will "complete" but it won't upload the cert properly.

**Comment by Technolero** [comment]
Also, if you have a cert chain, you might need to append them all together, that is what I did after the same issue.
