### ISSUE TITLE
There was an issue creating /data/dev-sas-aks as requested: [Errno 13] Permission denied: b''/data/dev-sas-aks

### ISSUE THREAD

**Issue by tclehman** [sassoftware/viya4-deployment#344]
I'm getting a permission denied error on deployment. I get the same error when I run the uninstall as well.

Error message:

![image](https://user-images.githubusercontent.com/49881073/203153739-6ffbe3e8-9358-4a13-a562-c1591e42e03c.png)

Deployment script:

> sudo docker run --rm \
--group-add root \
--user $(id -u):$(id -g) \
--volume /deployments:/data \
--volume /home/jumpuser/viya4-deployment/ansible-vars.yaml:/config/config \
--volume /home/jumpuser/devsasviya/terraform.tfstate:/config/tfstate \
--volume $HOME/.ssh/kp-dev-sas.pem:/config/jump_svr_private_key \
viya4-deployment --tags "baseline,viya,install"

I'm not sure how to troubleshoot this. It can't create the folder but I have no access to the host its trying to create on. How do I fix this?

**Comment by thpang** [comment]
In your /deployments directory is there a dev-sas-ask directory? Seems like it's trying to create a file when the directory is present. This can happen when you run docker with the volume command and it has nothing the volume actually has to mount so it creates the directory.

**Comment by tclehman** [comment]
There is not, the directory is empty:

![image](https://user-images.githubusercontent.com/49881073/203156942-df0d5f89-ce3b-4d4e-a0e9-a6dd3e43714d.png)

**Comment by tclehman** [comment]
The issue was that - for some unknown reason - the /deployments directory was not created with enough permissions. It was created with 755 permissions. When changing it to 777 permissions, the deployment proceeded past that task.
