### ISSUE TITLE
Deployment URL not loading Viya

### ISSUE THREAD

**Issue by tclehman** [sassoftware/viya4-deployment#347]
------------UPDATE------------
After further troubleshooting, we have found the problem, however unsure of the solution still.

The problem is that - for some reason - the number of pods on the stateless VM is being scaled up to the max amount specified of 110. This is the default number that comes with the IAC repository.

![image](https://user-images.githubusercontent.com/49881073/204904006-07d90ce3-74e9-46b4-ac0c-de8beee37be5.png)

There are 110 Network interfaces associated with this VM scale set, and only 1 actually works. When using the correct IP address, we can in-fact get a SAS Logon screen, the other 109 don't work. There should only be one though. Why is this VM scale set maxing out the pods when we've done nothing but deploy the environment?

------------END UPDATE------------
I have just finished the deployment script for the environment. All pods and nodes are running and appear to be in a healthy state. 

Problem:
After deployment, the URL we would use to access the web application is not returning anything. The DNS record resolves to the IP address properly as expected; however the SAS Logon page does not load

Troubleshooting:
I have uninstalled / reinstalled Viya. We have compared the Azure Marketplace environment to the environment in question here. We noted that each Kubernetes node was taking 100+ IP addresses, where the Marketplace environment only used 1 per node.:
![image](https://user-images.githubusercontent.com/49881073/204634814-603aa2e0-f9fa-4ea7-a7fe-b7016e2b5027.png)

We also noticed that the Marketplace environment, as well as my own test environment, both had their health probes return from the AKS-SYSTEM node as healthy, whereas in this environment it does not.

Marketplace:
![image](https://user-images.githubusercontent.com/49881073/204634843-0217af12-d946-4483-acc7-c083045635b7.png)

Problematic Environment:
![image](https://user-images.githubusercontent.com/49881073/204634882-35eb106c-7a34-4c5e-bd44-655386320bd7.png)
This suggests some discrepancy in the customer environment that the marketplace deployment / my personal deployment don’t contain. We can use both environments to compare against as needed.

**Comment by thpang** [comment]
I've setup a cluster myself and only see the 1 interface we create not an interface per pod count. Is this an instance where you've altered the configuration values for the pods? Or are you supplying your own network items? It's kinda hard to tell. If needed reach out and set up a 30 minute meeting and we can go over the setup. I'll be OOTO on 12.2.2022 but check my calendar for Mon/Tue of next week.

**Comment by tclehman** [comment]
We fixed it – the guy we were working with who was hosting the infrastructure said there was some mismatch with the infrastructure settings. They were bringing their own network rather than having the code deploy it all.

I will get up with him at a later date and hopefully add some details on the issue/fix as I don’t fully understand what was wrong yet.

**Comment by riragh** [comment]
Based on the last comment, user was able to resolve the issue. Closing this issue.
