### ISSUE TITLE
Error when running the docker command

### ISSUE THREAD

**Issue by makane-sas** [sassoftware/viya4-deployment#377]
I am running the following command: ansible-playbook \
  -e BASE_DIR=/sas/viya4/viya4-deployment  \
  -e CONFIG=/sas/viya4/viya4-deployment/ansible-vars-iac.yaml \
  -e TFSTATE=/sas/viya4/viya4-iac-azure/terraform.tfstate \
  -e JUMP_SVR_PRIVATE_KEY=/home/makane/.ssh/id_rsa.pub \
    playbooks/playbook.yaml --tags "baseline,viya,cluster-logging,cluster-monitoring,viya-monitoring,install" 
No matter what I do, I am getting this error message: Unable to find image 'viya4-deployment:latest' locally
Trying to pull repository registry.access.redhat.com/viya4-deployment ...
Pulling repository registry.access.redhat.com/viya4-deployment
Trying to pull repository registry.redhat.io/viya4-deployment ...
Trying to pull repository docker.io/library/viya4-deployment ...
Trying to pull repository docker.io/library/viya4-deployment ...
/usr/bin/docker-current: repository docker.io/viya4-deployment not found: does not exist or no pull access.
See '/usr/bin/docker-current run --help'.

**Comment by Shiv-Y** [comment]
We also receive similar kind of an issue where it is failing to deploy via baseline. seems it is trying to connect to red hat and looking image tagged with latest from [repos] (viya4-deployment:latest) instead of local repository. But we are unable to find out the location where we can update it to point to correct location. So still trying to figure it out.

**Comment by jarpat** [comment]
Hey @makane-sas 

The image does not exist in the Docker public repository, you will need to build it on your host using the provided Dockerfile in this repo.

Dockerfile: https://github.com/sassoftware/viya4-deployment/blob/main/Dockerfile

`docker build -t viya4-deployment .`

See documentation here for Docker Usage: https://github.com/sassoftware/viya4-deployment/blob/main/docs/user/DockerUsage.md

**Comment by makane-sas** [comment]
Thank you so much!!!

**Comment by jarpat** [comment]
Closing, resolved.
