### ISSUE TITLE
VIYA 4.0 Installation - Azure VPN Enabled Subscription

### ISSUE THREAD

**Issue by jamesr26** [sassoftware/viya4-deployment#394]
Build Machine: jps-test.unx.sas.com
Kubernetes Cluster being created with: https://gitlab.sas.com/tosher/viya4-iac-vpn (Works everytime)
Using the following to perform installation:

viya4iac=/opt/sas/install/viya4-iac-azurefeb2023
viya4dep=/opt/sas/install/viya4-deployment
viya4base=/opt/sas/install/
viya4ns=${viya4base}/viya4-txdps/spurs
TFVARS=${viya4iac}/txdps.tfvars
TFPLAN=${viya4iac}/txdps.plan
export KUBECONFIG=${viya4iac}/mtljmu-txdps-viya4-aks-kubeconfig.conf

cd ${viya4dep}
ansible-playbook -vvv \
-e BASE_DIR=${viya4base} \
-e CONFIG=${viya4ns}/ansible-vars.yaml \
-e TFSTATE=${viya4iac}/terraform.tfstate \
-e JUMP_SVR_PRIVATE_KEY=$HOME/.ssh/id_rsa \
playbooks/playbook.yaml --tags "baseline,viya,install"

Keeps failing at this stage here:
TASK [vdm : kustomize - Get user's customizations] **************************************************************************************************************************
task path: /opt/sas/install/viya4-deployment/roles/vdm/tasks/kustomize.yaml:33
fatal: [localhost]: FAILED! => {
    "msg": "Unable to import siteconfig_info due to invalid syntax"
}

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=102  changed=10   unreachable=0    failed=1    skipped=101  rescued=0    ignored=0

Has anyone come across this? and what is the requirement it is looking for to be present?

**Comment by riragh** [comment]
@jamesr26, Are you still having this issue?
Azure VPN Enabled Subscription has not been part of IAC testing yet, so difficult to tell if this setup has anything missing.

**Comment by jamesr26** [comment]
Azure VPN Enabled VIYA 4.0 06-2023 tested and working. This is now resolved.
