### ISSUE TITLE
Failed to deploy internal postgres

### ISSUE THREAD

**Issue by shahjayl** [sassoftware/viya4-deployment#400]
Hi All, I am getting the below error and it fails the deployment using this project viya4-deployment.

I do have the following architecture i.e. default, system, cas, stateless, stateful, compute.

{"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'internal'\n\nThe error appears to be in '/home/jumpuser/viya4-deployment/roles/vdm/tasks/postgres/postgres.yaml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

Anyone please help me to resolve this?

**Comment by dhoucgitter** [comment]
Hi @shahjayl, could you share what you've defined in your ansible-vars for the V4_CFG_POSTGRES_SERVERS map? Consult CONFIG-VARS.md [here ](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md?plain=1#L239-L241)for an example and check that you don't have missing values or incorrect yaml indentation for that map.

If you are aiming to deploy Viya with the default platform internal postgres instance with no overrides, this would be a valid configuration.

```yaml
V4_CFG_POSTGRES_SERVERS:
  default:
    internal: true
```

**Comment by shahjayl** [comment]
Hi @dhoucgitter, I have specified as below:
V4_CFG_POSTGRES_SERVERS:
  default:
      internal: true
    postgres_pvc_storage_size: 10Gi
    postgres_pvc_access_mode: ReadWriteOnce
    postgres_storage_class: pg-storage
    backrest_storage_class: pg-storage

**Comment by dhoucgitter** [comment]
With regards to indentation, are you preserving the required indentation shown in CONFIG-VARS.md? default needs to be indented one level from V4_CFG_POSTGRES_SERVERS, internal and the other values need to be indented to an additional level.
Take a look here for required indentation https://github.com/sassoftware/viya4-deployment/blob/main/examples/ansible-vars.yaml#L36, but you'd want to se internal: true

**Comment by shahjayl** [comment]
I am facing this issue as Container Registry password is containing special character { and #. @dhoucgitter any idea how can we pass this value without parsing? I have tried to keep direct value without quotes, with quotes, between {% raw %} {% endraw %}. However nothing has been worked.

**Comment by shahjayl** [comment]
I tried the above method as well but no luck, it's giving similar error as below:

ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes

**Comment by dhoucgitter** [comment]
@shahjayl, anticipating that the updates made in #421 will solve this issue. Look for it in an upcoming release.

**Comment by jarpat** [comment]
Closing, implemented in the 6.5.0 release
https://github.com/sassoftware/viya4-deployment/releases/tag/6.5.0
