### ISSUE TITLE
SAS Deployment Operator is getting Failed

### ISSUE THREAD

**Issue by shahjayl** [sassoftware/viya4-deployment#408]
While running ansible command, I am getting the following error:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Logging into cr.sas.com for user 9CV4JS failed - 500 Server Error for http+docker://localhost/v1.41/auth: Internal Server Error (\"Get \"[https://cr.sas.com/v2/\](https://cr.sas.com/v2/)": unauthorized: incorrect username or password\")"}

Though it's taking the credentials from the secrets.yaml

Anyone is having an idea on this or faced the same then please update me with the resolution. Thanks in advance!

**Comment by dhoucgitter** [comment]
What release version of DAC are you using? Could you check out this Troubleshooting tip and validate that you have the required version of the Docker daemon running on the workstation you are running DAC from? Here is the text from the solution of that troubleshooting entry:

> As of [release 6.0.0](https://github.com/sassoftware/viya4-deployment/releases/tag/6.0.0), it's required that if you are running this project using Ansible directly on your workstation, it needs Docker to be installed and the executing user should be able to access it. This is so that we can consume the [sas-orchestration tool](https://go.documentation.sas.com/doc/en/itopscdc/default/dplyml0phy0dkr/p0nid9gu3x2cvln1pzpcxa68tpom.htm#p1garxk7w4avg2n1hd6e4nt5kks7), which is available as a Docker image to generate the [SASDeployment Custom Resource file](https://go.documentation.sas.com/doc/en/itopscdc/default/dplyml0phy0dkr/p0nid9gu3x2cvln1pzpcxa68tpom.htm#p012wq5dhcqbx8n12abyqe25m4nu)
