### ISSUE TITLE
Document upgrade steps

### ISSUE THREAD

**Issue by bek-afs** [sassoftware/viya4-deployment#424]
Hello,

I am having trouble finding clear instructions for the upgrade process when SAS Viya is installed using this repo. I saw issue #135 that is related to this, but the issue is ~2 years old and mentions that the deployment operator had not yet been integrated. To my knowledge, the deployment operator is now integrated with this repo. 

Therefore, is it intended that we'd follow the [Using the Deployment Operator](https://documentation.sas.com/doc/en/itopscdc/v_038/k8sag/n0s8d167fprb2pn118n4dc25lpmv.htm) upgrade steps? If so, I believe we'd have to follow Option 2 of creating and applying the SASDeployment Custom Resource, since I don't believe that was generated on the initial deployment using this repo. 

Or, are we able to just supply the new deployment assets and re-run the original `docker run` command with the `viya,install` tags? [1]

It would be helpful if this repo could document if it is only meant to initially deploy SAS Viya, or if it can be used for upgrades as well. And in either case, either directly documenting in this repo or pointing to SAS docs how those upgrades should be performed. In the meantime, hoping I can get some clarification on the recommended upgrade process. Thanks!

[1] [DockerUsage readme](https://github.com/sassoftware/viya4-deployment/blob/main/docs/user/DockerUsage.md#running)

**Comment by dhoucgitter** [comment]
The link that you reference contains the Best Practices and Guidelines for updating as well as the different methods that can be used to update to a new version. Each method has its own set of steps. This [section ](https://github.com/sassoftware/viya4-deployment#updating-sas-viya-manually) in the viya4-deployment README also has some additional advice and it references the link to the manual update instructions that you referenced above.

**Comment by bek-afs** [comment]
Thanks for the responses here! 

Just wanted to close out this loop with how we've implemented our initial deployments and upgrades (using the deployment operator method). We perform the initial deployment using this repo. To upgrade, we perform any prep tasks (e.g. reading release notes, making any changes to config files, downloading new deployment assets and images, etc). Then we [redeploy the deployment operator](https://go.documentation.sas.com/doc/en/sasadmincdc/v_041/dplyml0phy0dkr/n137b56hwogd7in1onzys95awxqe.htm#n1ozze6vebu3bkn1c2i3kt44qwa1) (technically this isn't required for every upgrade, but we do so anyways to ensure we have the latest version of the deployment operator), we create the [SASDeployment Custom Resource](https://go.documentation.sas.com/doc/en/sasadmincdc/v_041/dplyml0phy0dkr/p0nid9gu3x2cvln1pzpcxa68tpom.htm#p012wq5dhcqbx8n12abyqe25m4nu), and then [apply it](https://go.documentation.sas.com/doc/en/sasadmincdc/v_041/dplyml0phy0dkr/p127f6y30iimr6n17x2xe9vlt54q.htm#p0lhaw04t8hfhjn1cn1gadt5gbph).

I think this can be closed out from my perspective!
