### ISSUE TITLE
Domains that need to be registered on EKS in a proxy environment

### ISSUE THREAD

**Issue by shiokshin** [sassoftware/viya4-deployment#426]
I would like to install SAS viya on our EKS, which is connected to the internet via a proxy.
We use zscaler(cloud proxy) and I need to register specific domains to be able to install and use SAS viya.
Could you provide me a list of the domains that need to be registered for this purpose?

**Comment by jarpat** [comment]
Hey,
Does the documentation around the ingress FQDN here to set your domain help?
https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#ingress

**Comment by jarpat** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
