### ISSUE TITLE
Suggestion: publish docker images

### ISSUE THREAD

**Issue by momiji** [sassoftware/viya4-deployment#436]
Hello,

is it possible to publish prebuilt docker images, based on tags for example, in **dockerhub** and **ghcr** (github container registry), like this: https://github.com/users/momiji/packages/container/viya4-deployment/versions.

I don't think it is important to worry about the viya-deployment ansible playbook included in the docker image (which is still required because build relies on `requirements.txt`), as we can override it during runtime:
- mount volume as /viya4-deployment.new
- rsync from /viya4-deployment.new to /viya4-deployment without removing .ansible
- any extra required steps, like injecting additional ca certificates

My usage is something like this:

```
$ docker run --rm -it
    ... \
    -v $PWD/viya4-deployment:/viya4-deployment.new:ro \
    -v $PWD/viya4-entrypoint.sh:/viya4-entrypoint.sh:ro \
    ... \
    --entrypoint $PWD/viya4-entrypoint.sh \
    sassoftware/viya4-deployment:6.4 \
    --tags install,viya
```

with a viya4-entrypoint.sh like this:

```
#!/usr/bin/env bash
set -ex

[ -d /ca-certs/ ] && {
    install -m 0750 -d /usr/local/share/ca-certificates/ca-certs/
    ls /ca-certs/ | xargs -i cp /ca-certs/{} /usr/local/share/ca-certificates/ca-certs/{}.crt
    update-ca-certificates
}

[ -d /viya4-deployment.new/ ] && {
    rsync -a /viya4-deployment.new/ /viya4-deployment/ --delete --exclude /.ansible
}

chmod +x /viya4-deployment/docker-entrypoint.sh

cmd=/viya4-deployment/docker-entrypoint.sh
[ "${1:-}" = "bash" ] && cmd=/bin/bash && shift

exec $cmd "$@"
```

**Comment by jarpat** [comment]
This requires PM review

**Comment by momiji** [comment]
Hum, can you give more information on the legal/support reasons?
I was feeling it to just be a docker image with pre-installed requirements and nothing more.

I'm intersted because as I do publish the images for my own usage, you've just worried me...
