### ISSUE TITLE
playbook.yaml error during baseline install check

### ISSUE THREAD

**Issue by hobsas** [sassoftware/viya4-deployment#438]
Hi,

During the baseline install check I have the following issue:

viya4-deployment --tags "baseline,install" --check

TASK [Delete tmpdir] ************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'path'

    The error appears to be in '/viya4-deployment/playbooks/playbook.yaml': line 81, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

            - baseline
        - name: Delete tmpdir
          ^ here

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=26   changed=3    unreachable=0    failed=1    skipped=68   rescued=0    ignored=0

**Comment by dhoucgitter** [comment]
@hobsas, could you add which DAC release version you noticed this with and the IaC provider and version that you are using, thanks.

**Comment by dhoucgitter** [comment]
@hobsas, I discussed this with our project's architect and discovered that outside of two onboard/offboard tasks for multi-tenancy, viya4-deployment tasks do not support the use of the Ansible --check option. Can you comment on what your use case for running --check mode is? One nice thing about the baseline set of tasks is that it runs in just a few minutes so if you'd just like to see the tasks that "baseline,install" will run, you could run a "baseline,install" followed by "baseline,uninstall" along with the -v option to get a good idea of what happens during that phase given your cloud provider environment.

**Comment by jarpat** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
