### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by varsovik** [sassoftware/viya4-deployment#44]
Docker build failed.  Received the following error:
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl3-gnutls_7.68.0-1ubuntu2.2_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I had to run `sudo apt update` before  the required packages could be installed.
I added the follwing line to the Dockerfile:

RUN apt update

Afterwards I was able to build the Docker image.

Thanks.

**Comment by NormJohnIV** [comment]
The docker file already has an apt-get update. Also, from testing, we had no issue building the dockerfile. Are you still having this issue? if so, can you provide the dockerfile you are using and steps to replicate?

**Comment by varsovik** [comment]
No I did yesterday a new build and it ran ok. Thanks.
