### ISSUE TITLE
Oracle database driver on CAS nodes

### ISSUE THREAD

**Issue by biohazd** [sassoftware/viya4-deployment#458]
Is there an easier way to add the Oracle database driver to the cas nodes ?

I’m on AWS and using an Oracle RDS server.

I found this video 
https://youtu.be/mTT8K-UuHGw

**Comment by jarpat** [comment]
There is currently no variable or toggle in the `viya4-deployment` that will configure the Oracle database drives for you. Aside from that youtube video you could take a look at the doc present at `sas-bases/examples/data-access/README.md` in your deployment assets.
