### ISSUE TITLE
Question: how do I add more cas nodes/pods

### ISSUE THREAD

**Issue by biohazd** [sassoftware/viya4-deployment#477]
Hi

I have deployed the EKS cluster and set it to use 2 cas instances(pods). This works great.

how do I add more cas pods to the cluster?  Do I edit the terraform/Ansible vars file to increase workers and redeploy ?

**Comment by jarpat** [comment]
Hey @biohazd,

The answer depends on how your infrastructure is currently configured.

If during infrastructure creation in `viya4-iac-aws` you configured the `max_nodes` for your CAS node pool to already be the target number of CAS nodes you desire or greater, all you have to do is update the [`V4_CFG_CAS_WORKER_COUNT`](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#cas) in your `ansible-vars.yaml` and rerun the `viya,install` tasks. As more CAS worker pods come up EKS will provision up to  `max_nodes` for the CAS pods to run on.

The Viya deployment does not need to be restarted either to add more workers, see:
* https://documentation.sas.com/?cdcId=sasadmincdc&cdcVersion=default&docsetId=dplyml0phy0dkr&docsetTarget=n08u2yg8tdkb4jn18u8zsi6yfv3d.htm#p1e5ki5ufxjdcjn1wo86hu5181zw
* `sas-bases/examples/cas/configure/README.md` In your deployment assets

Also, see `viya4-iac-aws` example file for `max_nodes` setting https://github.com/sassoftware/viya4-iac-aws/blob/main/examples/sample-input.tfvars#L48

---

Alternatively, if your `max_nodes` is not enough to reach the number of CAS nodes you desire. I would recommend doing the following.
1. Run the cron job to stop the Viya deployment https://documentation.sas.com/?cdcId=sasadmincdc&cdcVersion=v_046&docsetId=calchkadm&docsetTarget=p17xfmmjjkma1dn1b5dcx3e5ejxq.htm#p0butgo7gtfyi0n14umtfv0voydt
2. In your `terraform.tfvars` file from the `viya4-iac-aws` project adjust `max_nodes` for the CAS node pool
3. Run `terraform apply` to apply these changes
4. Run the cron job to start the Viya deployment https://documentation.sas.com/?cdcId=sasadmincdc&cdcVersion=v_046&docsetId=calchkadm&docsetTarget=p17xfmmjjkma1dn1b5dcx3e5ejxq.htm#p0butgo7gtfyi0n14umtfv0voydt
5. Update the [`V4_CFG_CAS_WORKER_COUNT`](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#cas) in your `ansible-vars.yaml` to your desired count and rerun the `viya,install` tasks.

**Comment by jarpat** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
