### ISSUE TITLE
Documentation: add cadence <-> release versions compatibility

### ISSUE THREAD

**Issue by momiji** [sassoftware/viya4-deployment#479]
I would like to ensure we're always using the good release vs. the cadence we're deploying in our environments.

Unless this is absolutely not necessary, I was thinking of something like this:

| cadence | min release | max release | comment |
|-|-|-|-|
| 2023.02 | 6.0.0 | 6.4.0 |
| 2023.03 | 6.5.0 | latest | new version of kustomize |
...
| 2023.07 | 6.5.0 | latest |
| 2023.08 | 6.10.0 | latest |

**Comment by jarpat** [comment]
This requires PM review

**Comment by jarpat** [comment]
Currently no plans to add that table; however, the latest `viya4-deployment` release should always support all currently supported stable and LTS cadences. You may have to adjust versions of [third party tools](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#third-party-tools) based of cadence requirements, but the deployment should still execute successfully.

See SAS Viya platform releases.
https://documentation.sas.com/?cdcId=itopscdc&cdcVersion=default&docsetId=itopswn&docsetTarget=p0c2ug2w8ypmq0n1128c1j3a9i5v.htm
