### ISSUE TITLE
Client Access variable value from sas-access.properties file not getting applied to Compute and CAS container Pod. 

### ISSUE THREAD

**Issue by UttamSAS** [sassoftware/viya4-deployment#489]
### Viya4 Deployment Version Details

I am using the latest version 6.11.0 ( release date Aug 18th).

### Steps to Reproduce

I am using the Viya4 deployment operator to deploy the Viya 4 environment. 

Under the deployment folder place a file as  ..../${NS}/site-config/data-access/sas-access.properties  with few Access Client variable  like as follows : 

##########################
# SAS/ACCESS to ODBC
##########################
ODBCINI=/mnt/viya-share/config/access-clients/odbc/odbc.ini
AWS_CREDENTIAL_PROFILES_FILE=/mnt/viya-share/config/access-key/credentials
MYSQL=/mnt/viya-share/config/access-clients/odbc/mysql/lib

=====
Execute the VIya4 deployment using the deployment Operator as follows . 
======

viya4deployment="docker container run -i --group-add root --user 1000:981 -v /home/cloud-user/project/deploy:/data -v /home/cloud-user/.kube/config:/
config/kubeconfig -v /home/cloud-user/project/deploy/gelenv/install-vars.yaml:/config/config -v /home/cloud-user/viya4-iac-aws/utk204.tfstate:/config
/tfstate viya4-deployment"

${viya4deployment} --tags "baseline,viya,install"

### Expected Behavior

The sasdeployment.yaml file generated by the deployment operator process should have an entry for  ..../site-config/data-access/sas-access.properties  file with all the variables. 

The kustomization.yaml should have an entry for ....../site-config/data-access/sas-access.properties under config- map-generator section, but there isn't any!

 

### Actual Behavior

The kustomization.yaml does not get an entry for ....../site-config/data-access/sas-access.properties under config- map-generator section. It seems due to this reason, the Client Access variable does not get applied to the Compute and CAs container pod. 

### Additional Context

If I place the Client Access variable in a .yaml file under ./site-config/data-access/ for both the Compute and CAS engine,  I can see the variable value gets applied to Compute and CAS container pods. 

[cloud-user@pdcesx03204 data-access]$ more set-compute-client-access.yaml
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
 name: sas-compute-server-config
behavior: merge
literals:
 - ODBCINI=/mnt/viya-share/config/access-clients/odbc/odbc.ini
 - AWS_CREDENTIAL_PROFILES_FILE=/mnt/viya-share/config/access-key/credentials
 - MYSQL=/mnt/viya-share/config/access-clients/odbc/mysql/lib
[cloud-user@pdcesx03204 data-access]$

[cloud-user@pdcesx03204 cas-server]$ more setcasnodetimeout.yaml
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
 name: sas-cas-config
behavior: merge
literals:
 - CAS_NODE_CONNECT_TIMEOUT=1800
 - ODBCINI=/mnt/viya-share/config/access-clients/odbc/odbc.ini
 - AWS_CREDENTIAL_PROFILES_FILE=/mnt/viya-share/config/access-key/credentials
 - MYSQL=/mnt/viya-share/config/access-clients/odbc/mysql/lib

[cloud-user@pdcesx03204 cas-server]$

    

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by biohazd** [comment]
also deploy this file, then sas properties will work

 **cat site-config/data-access/configmaps.yaml**
```
apiVersion: builtin
kind: ConfigMapGenerator
behavior: merge
metadata:
  name: sas-access-config
envs:
  - site-config/data-access/sas-access.properties
```

**Comment by jarpat** [comment]
@UttamSAS did the previous response from @biohazd resolve your issue?

**Comment by UttamSAS** [comment]
@jarpat  yes! it did resolve the issue.
