### ISSUE TITLE
fix: (IAC-1242) where are V4_CFG_RWX_FILESTORE_ASTORES_PATH and  V4_CFG_RWX_FILESTORE_BIN_PATH variables actually being used in this project?

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-deployment#493]
### Viya4 Deployment Version Details

Deploy on Azure

### Steps to Reproduce

Deploy SAS Viya 4 on Azure using a Jump server and an NFS Server

### Expected Behavior

I would expect the V4_CFG_RWX_FILESTORE_ASTORES_PATH and V4_CFG_RWX_FILESTORE_BIN_PATH variables to be used somewhere in the deployment but cannot find any such usage.
Can someone please tell me?

### Actual Behavior

No usage found for these defined variables in the deployment files

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayeun** [comment]
Have you looked at https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#storage ?

**Comment by miaeyg** [comment]
Yes, I am aware that these options are documented but I cannot find anywhere within the project where they are actually being used. I searched all files for these two variables and got zero results. I am wondering if these options are being used at all...
