### ISSUE TITLE
AWS Autoscaler to use a cluster type placement group for CAS node pool

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-deployment#517]
Is there a way to make the deployed AWS EKS Autoscaler to use a "cluster" type AWS placement group for the CAS node pool?

**Comment by dhoucgitter** [comment]
Hi @miaeyg. DAC mainly deals with the version of the autoscaler Helm chart that gets installed while the node pool definitions and autoscaling behavior are handled in the viya-iac-aws project. I believe the response to issue https://github.com/sassoftware/viya4-iac-aws/issues/259 applies here also.
