### ISSUE TITLE
Namespace for external PostgreSQL servers (AWS RDS)

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-deployment#519]
Looking at the doc here https://github.com/sassoftware/viya4-deployment/blob/4ef910891e6d6e6dca0bccbb7fd013c93a589ae0/docs/CONFIG-VARS.md#postgresql I do not see any option to set the namespace for the external PostgreSQL server (AWS RDS in my case). Please correct me if I am wrong.

According to https://documentation.sas.com/doc/en/sasadmincdc/v_045/itopssr/p05lfgkwib3zxbn1t6nyihexp12n.htm#p1wq8ouke3c6ixn1la636df9oa1u  it is _required_ to install the external PG on a separate namespace than the SAS namespace:

> Deploy the PostgreSQL instance in a separate namespace from the SAS Viya platform deployment. Installing non-SAS software in the SAS Viya platform namespace is not supported.

How is this requirement handled in this project?

**Comment by miaeyg** [comment]
The more I think it seems this question is irrelevant for AWS RDS as it is not in any namespace at all, right?

**Comment by dhoucgitter** [comment]
> The more I think it seems this question is irrelevant for AWS RDS as it is not in any namespace at all, right?

Correct, the external AWS RDS instance is not running within the K8s cluster.
