### ISSUE TITLE
How to upgrade ingress-nginx controller installed using this DaC project on an existing SAS Viya deployment running on Azure?

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-deployment#529]
I used this project to install SAS Viya on Azure a few months ago and now I need to upgrade my K8S cluster version to be inline with SAS Viya requirements however this upgrade forces also an upgrade of the ingress-nginx controller that is installed on this same cluster.
The ingress-nginx current version is 1.7.0 and was installed using this DaC project (with the "baseline" Ansible tag).
Question is what is the proper way to upgrade the ingress-nginx version from 1.7.0 to the latest version 1.9.6? Can I re-run this project with the "baseline,install" tags to force an upgrade?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, yes, you should be able to re-run "baseline,install" using a version of DAC with a newer ingress-nginx default version to upgrade ingress-nginx to the latest.

**Comment by miaeyg** [comment]
Thanks @dhoucgitter closing this issue
