### ISSUE TITLE
Support for EKS 1.29

### ISSUE THREAD

**Issue by bek-afs** [sassoftware/viya4-deployment#537]
### Is your feature request related to a problem? Please describe.

Version 6.18.1 of this project uses kubectl version 1.27.11 [1]. AWS EKS is currently on version 1.29, which was released on 1/23/24 [2]. Kubectl must be within one minor version of Kubernetes [3], meaning kubectl 1.27.11 is compatible with Kubernetes 1.26-1.28. 

When will kubectl be upgraded to 1.28.x and 1.29.x? For reference, EKS 1.28 is out of standard support on 11/26/24.

[1] https://github.com/sassoftware/viya4-deployment/blob/226a143cd81a52bd530fd638c2b492c061611511/Dockerfile#L12
[2] https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar
[3] https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html

### Describe the solution you'd like

Upgrade to kubectl version 1.28.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riragh** [comment]
The kubectl version updates across repos is progress and will be released soon. See PR #538 for related work.

**Comment by riragh** [comment]
Changes were released to main, closing this issue.
