### ISSUE TITLE
Upgrading the kubectl version in cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-orchestration:1.116.2-20240312.1710256388641

### ISSUE THREAD

**Issue by lthebe** [sassoftware/viya4-deployment#569]
### Viya4 Deployment Version Details

While I am trying to deploy the sas viya, I get this error:
{"level":"info","version":1,"source":"sas-orchestration","messageKey":"sas-orchestration.lifecycle.operation.log","messageParameters":{"log":"version difference between client (1.27.9) and server (1.29.6-gke.1326000) exceeds the supported minor version skew of +/-1\n"},"properties":{"logger":"internal/lifecyclehelper","caller":"lifecyclehelper/lifecyclehelper.go:111"},"timeStamp":"2024-08-22T08:44:10.585277+00:00","message":"version difference between client (1.27.9) and server (1.29.6-gke.1326000) exceeds the supported minor version skew of +/-1\n"} Is there any option to control the version of this kubectl? Or I just need to downgrade my kubernetes cluster? 

The pods that I am getting error:
sas-deployment-operator-reconcile-2664fc69-7cvhf   0/1     Error     0          10m
sas-deployment-operator-reconcile-2664fc69-cw6xd   0/1     Error     0          13m
sas-deployment-operator-reconcile-2664fc69-dkwvv   0/1     Error     0          15m

The image that is being used: cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-orchestration:1.116.2-20240312.1710256388641

### Steps to Reproduce

Setup the gke (with viya4-iac-gcp setting kubernetes_channel "STABLE") and run the ansible-playbook command to deploy the viya.

### Expected Behavior

Expected behavior is deployment operator starts deploying the Viya in the cluster.

### Actual Behavior

Deployment itself is successful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ephesused** [comment]
@lthebe, based on the sas-orchestration version number, it looks like you're trying to deploy LTS 2024.03. The support range for 2024.03 is k8s 1.26 - 1.28.

**Comment by lthebe** [comment]
@ephesused Thank you very much.
