### ISSUE TITLE
aws-iam-authenticator no longer used, remove references from Dockerfile

### ISSUE THREAD

**Issue by kevinlinglesas** [sassoftware/viya4-deployment#67]
I was told that aws-iam-authenticator was no longer used.  I see ARG related to the version and a curl pulling down aws-iam-authenticator in the Dockerfile.   Shouldn't this be removed?

**Comment by NormJohnIV** [comment]
viya4-iac-aws no longer requires aws-iam-authenticator. However, we support any BYO cluster. So, we need to keep it in case a customer brings a cluster that uses it.
