### ISSUE TITLE
What to put into LOADBALANCER_SOURCE_RANGES in ansible-vars.yaml

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya4-deployment#76]
I am confused by the instructions ... in the file, `/home/jumpuser/viya4-deployment/ansible-vars.yaml` which was copied from `/home/jumpuser/viya4-deployment/examples/ansible-vars-iac.yaml`

Should I put the value from the IAC tf apply command output:
`nat_ip = 52.188.xxx.xxx`

into line 6: 
`LOADBALANCER_SOURCE_RANGES: ['52.188.xxx.xxx/32']`

**Comment by thpang** [comment]
The file states that you should. Listed here in the sample file: https://github.com/sassoftware/viya4-deployment/blob/main/examples/ansible-vars-iac.yaml#L4-L6

**Comment by andybouts** [comment]
Thanks for clarification.  It was not clear to me before.  I'll probably suggest a clarification via a PR to make it a tad easier for others.

**Comment by cceeci99** [comment]
can you explain why i must set <desired cidrs> to the nat ip from the tf output? shouldn't i put the service cidr that is showing in the aks overview ?

**Comment by thpang** [comment]
The `nat_ip` value gets set in the valid CIDR ranges for your security group, firewall, etc. depending on your provider to allow north/south traffic back into the cluster.

**Comment by cceeci99** [comment]
However this approach still exposes the service to public IP because of nginx ingress controller, i want to find new approach that uses azure VPN maybe and to set the IP to be private, what changes i need to do any advice?
