### ISSUE TITLE
Change order of deployment task execution

### ISSUE THREAD

**Issue by gsmith-sas** [sassoftware/viya4-deployment#77]
This project appears to deploy things in a set order of: baseline, viya, cluster-logging, cluster-monitoring, viya-monitoring.  I’d like to suggest you deploy things in a slightly different order.  In order to allow admins to use the [Viya 4 Monitoring for Kubernetes](https://github.com/sassoftware/viya4-monitoring-kubernetes) tools to monitor (and, potentially, debug) the Viya deployment process, I suggest things be deployed in the order of: baseline, cluster-logging, cluster-monitoring, viya, viya-monitoring.  I understand admins can control the deployment order by running the deployment command multiple times with different tasks identified in each.  But, if an admin specified all of the tasks, I think the revised order would provide a better user-experience.

**Comment by thpang** [comment]
The order provided does not indicate the order in which they are installed. baseline is always first, followed by the logging/monitoring bits. Then the Viya deployment is installed along with it's monitoring.
