### ISSUE TITLE
If you already pre-downloaded the deployment asset, do you still need to specify SAS API credentials?

### ISSUE THREAD

**Issue by pulungw** [sassoftware/viya4-deployment#80]
My understanding is the SAS Orders API  is used to download deployment assets, certificates, and license files. 

So if you already pre-downloaded the deployment asset and specify it with `V4_CFG_DEPLOYMENT_ASSETS` option, do you still need the SAS API credentials? Are they used somewhere else? 

The SAS API option `V4_CFG_SAS_API_KEY` and `V4_CFG_SAS_API_SECRET` has a required flag, so I wonder if it's necessary regardless if you're using pre-downloaded asset or not.

**Comment by thpang** [comment]
As the doc states: https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#sas-api-access they are required even if you have the assets already pulled down. What is the reason you already have them? The tooling is setup to pull what's requested?

**Comment by pulungw** [comment]
I downloaded the asset separately from my.sas.com. I’m doing this because I need to keep my mirror registry and the deployment asset in sync. 

What happened was my mirror registry was downloaded last week. But when I tried to deploy using this project today, it downloaded a newer asset that points to a newer release version under the same cadence (2020.1.4). 

It then tried to pull newer pod images version that I do not have in my mirror repository, so the pod failed. I thought mirror registry with the same cadence guarantees the same release version but that doesn’t seem to be the case... 

So I had to update my mirror registry today. I’m trying to prevent the same thing happening in the future. 

Is there any way to specify not just the cadence, but also which release version to pull with this project? (Like 20210417.159694358830)

Thanks.

**Comment by thpang** [comment]
Also if you have yown mirror manager you can use that information in these variables: https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#container-registry-access

**Comment by pulungw** [comment]
Yes, I already use that option like so, and it works like expected. It's pulling the container image from my ACR.
```bash
V4_CFG_CR_USER: <appId>       # Service principal Id
V4_CFG_CR_PASSWORD: <secret>      # Service principal secret
V4_CFG_CR_URL: viya4testacr.azurecr.io    # My mirror Azure Container Registry
V4_CFG_CADENCE_NAME: stable 
V4_CFG_CADENCE_VERSION: 2020.1.4
```

My problem was the container image that the tool is trying to pull is newer than what I have in my mirror registry, despite specifying the same cadence (2020.1.4), I've reached out to you internally.
