### ISSUE TITLE
adding sas-bases/overlays

### ISSUE THREAD

**Issue by Vladislaff** [sassoftware/viya4-deployment#81]
Hi,

How do I add the overlays from sas-bases/overlays?
As I understand I cannot add them to the kustomization.yaml since it is autogenerated.
I copied them to site-config and modified a little so they would be picked up by viya4-deployment, but this means that I need to manually sync them when I update to new releases.

**Comment by thpang** [comment]
@Vladislaff as long as you continue to deploy into the same cluster your modifications will be used. Here's the link to the doc on how to set this up: https://github.com/sassoftware/viya4-deployment#customizations

**Comment by Vladislaff** [comment]
I don't mean my customizations, but standard overlays.
For example, to deploy sas-planning I need to add its overlays to kustomization.
To do so with viya4-deployment I copied them over to site-config with some changes so it will be picked up by the tool.
Next month I download a new version of Viya and the overlay in sas-bases/overlays is different. How can I add the overlays from sas-bases without the need to modify and copy them to site-config?

**Comment by thpang** [comment]
For that you'd have to follow the docs provided by SAS, https://go.documentation.sas.com/doc/en/itopscdc/v_001LTS/itopswlcm/home.htm

**Comment by Vladislaff** [comment]
Does this mean I cannot use viya4-deployment if I need to use standard overlays from sas-bases/overlays?

**Comment by thpang** [comment]
It does not but you'll have to copy them as you stated above. What is the reason these `sas-bases` overlays need to be replaced? Is that something covered in the SAS doc link provided? If you're making changes most of those should be in the `site-config` location. Is there a reason they cannot exist there?
