### ISSUE TITLE
Do not reload the assets if already present

### ISSUE THREAD

**Issue by Vladislaff** [sassoftware/viya4-deployment#82]
Hi,

Can you add a feature that checks that the assets archive file of the requested version is already present in the namespace directory?
If yes then skip the steps which download it again from the orders api, delete existing sas-bases and unarchive the file.
I am running this tool in Azure Shell and it takes a lot of time for these steps which are unnecessary if I redeploy the same version multiple times.

These steps:
assets - Download
assets - Remove old files
assets - Extract downloaded assets
In https://github.com/sassoftware/viya4-deployment/blob/main/roles/vdm/tasks/assets.yaml

**Comment by NormJohnIV** [comment]
No. This is because the artifacts in the deployment assets are updated over time. You can, however, pass the tool your exciting asset file location and it will use it. https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#order
