### ISSUE TITLE
site-ph0 and site-ph1 generation

### ISSUE THREAD

**Issue by Vladislaff** [sassoftware/viya4-deployment#83]
Hi,

Could you add automatic generation on site-ph0.yaml and site-ph1.yaml alongside the site.yaml?
These will be generated with the respective lines in kustomization.yaml:
site-ph0.yaml:
transformers:
 - sas-bases/overlays/scaling/zero-scale/phase-0-transformer.yaml

site-ph1.yaml:
transformers:
 - sas-bases/overlays/scaling/zero-scale/phase-0-transformer.yaml
 - sas-bases/overlays/scaling/zero-scale/phase-1-transformer.yaml

This will be very useful for scaling the environment up and down without needing to regenerate them manually each time you update SAS.

**Comment by thpang** [comment]
@Vladislaff can you provide information on the `site-ph` files? There is no mention of these in the documentation for the deployment of SAS Viya 4. Thanks.

**Comment by Vladislaff** [comment]
I mean readily built phase 0 and phase 1 site.yaml files for scaling down.
Documentation here:
https://go.documentation.sas.com/doc/en/itopscdc/v_010/itopssrv/n0pwhguy22yhe0n1d7pgi63mf6pb.htm#p1nz12w805sz14n1rd6m593qnefy

Currently I have to rebuild them with every change manually.

**Comment by akashlunkad-sas** [comment]
I guess the request can be to build a start_all.sh and stop_all.sh to gracefully start and stop all services in viya4 
certainly a must have.

**Comment by Vladislaff** [comment]
I tried using the scaling features in \sas-bases\examples\kubernetes-tools\lifecycle-operations multiple times.
Once it corrupted the cacheserver, once consul and twice crunchy db. That was in 2020.1.1. Haven't tried it since.

**Comment by thpang** [comment]
Ok, if there are issues with the documentation tooling you may want to open an issue there.

**Comment by Vladislaff** [comment]
In 2021.1.1 cronjobs sas-start-all and sas-stop-all were added. No need for this anymore.
