### ISSUE TITLE
Load Balancer NAT Did not Auto-Parse and Use

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya4-deployment#85]
According to the [main page readme](https://github.com/sassoftware/viya4-deployment#terraform-state-file), the value for the `Cloud NAT IP address` should be automatically parsed and used.

The following line did not work in the ansible-vars.yaml and produced the following error:

`#LOADBALANCER_SOURCE_RANGES: ['x.x.x.x/32']  # but this did not automatically parse and pull from the IAC tfstate`

```
Error:
TASK [ingress-nginx : Deploy ingress-nginx] ************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {'controller': {'service': {'externalTrafficPolicy': 'Local', 'sessionAffinity': 'None', 'loadBalancerSourceRanges': '{{ loadBalancerSourceRanges }}'}, 'config': {'use-forwarded-headers': 'true'}, 'tcp': {}, 'udp': {}, 'lifecycle': {'preStop': {'exec': {'command': ['/bin/sh', '-c', 'sleep 5; /usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done']}}}, 'terminationGracePeriodSeconds': 600}}: {{ LOADBALANCER_SOURCE_RANGES }}: 'LOADBALANCER_SOURCE_RANGES' is undefined\n\nThe error appears to be in '/viya4-deployment/roles/ingress-nginx/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Deploy ingress-nginx\n  ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=24   changed=3    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0
```

In order to get past the error, I had to paste the following output from the CLI response from the `tf apply -auto-approve`:
nat_ip = 20.42.xxx.xxx

**Comment by thpang** [comment]
The sample file used when one is also using the IAC repos has the following items: https://github.com/sassoftware/viya4-deployment/blob/main/examples/ansible-vars-iac.yaml#L4-L6 . These items are needed in the file and parsed and replaced if they are found in the tfstate file supplied. As the README.md states [here](https://github.com/sassoftware/viya4-deployment#terraform-state-file)

_The ansible-vars-iac.yaml example file shows the values that need to be set when using the iac integration._

Not sure why you commented out that line. If you add the line back into your file things will work as expected.

**Comment by andybouts** [comment]
I had commented it out because the main readme that you linked indicated this field, `Cloud NAT IP address`, is parsed and used, but it seems those fields are not the same thing.  I'd like to request that the main readme use the same field names that the `ansible-vars.yaml` use.

**Comment by AWSmith0216** [comment]
This seems similar to internal issue IAC-208, although in that case the LOADBALANCER_SOURCE_RANGES was not commented out. Seems there is a bug in general with the parsing of the NAT IP, although that may be exclusive to using the internal viya4-deployment 'overlay'.

**Comment by andybouts** [comment]
﻿Thanks Adam, are you suggesting that instead of commenting out `LOADBALANCER_SOURCE_RANGES`, instead I should just leave it with the stock configuration of ` LOADBALANCER_SOURCE_RANGES: ['<desired_cidr_blocks>']` and it should perform the parsing for me?




From: Adam ***@***.***>
Date: Monday, May 3, 2021 at 10:53 AM
To: sassoftware/viya4-deployment ***@***.***>
Cc: Andy Bouts ***@***.***>, Author ***@***.***>
Subject: Re: [sassoftware/viya4-deployment] Load Balancer NAT Did not Auto-Parse and Use (#85)

EXTERNAL

This seems similar to internal issue IAC-208, although in that case the LOADBALANCER_SOURCE_RANGES was not commented out. Seems there is a bug in general with the parsing of the NAT IP, although that may be exclusive to using the internal viya4-deployment 'overlay'.

**Comment by AWSmith0216** [comment]
I believe that is what Thomas was suggesting, although personally I would assume that you want _something_ other than the NAT IP in the LOADBALANCER_SOURCE_RANGES. Set whatever your desired CIDRs are (your personal computer, company network, etc.) and the NAT IP should be parsed from the tfstate file and added to the user provided list if it's not already included.

My comment specifically was that even if you do that, I don't know if this functionality is working as intended. Refer to Jira IAC-208. I don't know if that issue is exclusive to using the internal viya4-deployment overlay, or also affects the official, external version.

**Comment by andybouts** [comment]
It will not work with the default value unchanged as it retained the sting and errored: <desired_cidr_blocks>

I am going to re-try with an empty list []:
LOADBALANCER_SOURCE_RANGES: [] # should automatically parse and pull from the IAC tfstate

Error:
TASK [ingress-nginx : Deploy ingress-nginx] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm --kubeconfig /tmp/ansible.kkhfg28r/.kube --namespace=ingress-nginx --version=3.20.1 --repo=https://kubernetes.github.io/ingress-nginx upgrade -i --reset-values --wait --create-namespace -f=/tmp/tmporn2b3h_.yml ingress-nginx ingress-nginx", "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"ingress-nginx\" does not exist. Installing it now.\n\nstderr: Error: Service \"ingress-nginx-controller\" is invalid: spec.LoadBalancerSourceRanges: Invalid value: \"[<desired_cidr_blocks> 52.149.xx.xx/32]\":



From: Adam ***@***.***>
Date: Monday, May 3, 2021 at 2:09 PM
To: sassoftware/viya4-deployment ***@***.***>
Cc: Andy Bouts ***@***.***>, Author ***@***.***>
Subject: Re: [sassoftware/viya4-deployment] Load Balancer NAT Did not Auto-Parse and Use (#85)

EXTERNAL

I believe that is what Thomas was suggesting, although personally I would assume that you want something other than the NAT IP in the LOADBALANCER_SOURCE_RANGES. Set whatever your desired CIDRs are (your personal computer, company network, etc.) and the NAT IP should be parsed from the tfstate file and added to the user provided list if it's not already included.

My comment specifically was that even if you do that, I don't know if this functionality is working as intended. Refer to Jira IAC-208. I don't know if that issue is exclusive to using the internal viya4-deployment overlay, or also affects the official, external version.

**Comment by andybouts** [comment]
Wait, I think I see what you are saying.

Are you saying that the ingress CIDR that was provided in the IAC is not retained here and it must be provided again?  Meaning:
LOADBALANCER_SOURCE_RANGES: [{the CIDR I provided to the IAC},{the parsed NAT IP from Terraform state}] # need to manually re-add your ingress CIDR and then this should automatically parse concatenate the NAT IP from the IAC tfstate

I was under the impression (right / wrong / otherwise) that the ingress CIDR from the IAC was retained and appended to a list including the parsed NAT IP that Terraform reported when the IAC completed so that it was fully automated.



From: Adam ***@***.***>
Date: Monday, May 3, 2021 at 2:09 PM
To: sassoftware/viya4-deployment ***@***.***>
Cc: Andy Bouts ***@***.***>, Author ***@***.***>
Subject: Re: [sassoftware/viya4-deployment] Load Balancer NAT Did not Auto-Parse and Use (#85)

EXTERNAL

I believe that is what Thomas was suggesting, although personally I would assume that you want something other than the NAT IP in the LOADBALANCER_SOURCE_RANGES. Set whatever your desired CIDRs are (your personal computer, company network, etc.) and the NAT IP should be parsed from the tfstate file and added to the user provided list if it's not already included.

My comment specifically was that even if you do that, I don't know if this functionality is working as intended. Refer to Jira IAC-208. I don't know if that issue is exclusive to using the internal viya4-deployment overlay, or also affects the official, external version.

**Comment by AWSmith0216** [comment]
None of the CIDRs provided to the IAC pieces is retained. You'll need to duplicate the 'default_public_access_cidrs' values in the ansible-vars-iac.yaml. Only the NAT IP will be parsed from the tfstate and appended to the list you provide.

**Comment by andybouts** [comment]
Yes, that’s be behavior that I observed.

I have a list of things to clarify in the documentation, so I’ll make changes and do a PR when I get time.

Appreciate the clarification.


From: Adam ***@***.***>
Date: Monday, May 3, 2021 at 3:04 PM
To: sassoftware/viya4-deployment ***@***.***>
Cc: Andy Bouts ***@***.***>, Author ***@***.***>
Subject: Re: [sassoftware/viya4-deployment] Load Balancer NAT Did not Auto-Parse and Use (#85)

EXTERNAL

None of the CIDRs provided to the IAC pieces is retained. You'll need to duplicate the 'default_public_access_cidrs' values in the ansible-vars-iac.yaml. Only the NAT IP will be parsed from the tfstate and appended to the list you provide.
